#!/usr/bin/env python3
"""Contract codegen — ONE plugin declaration -> the generated view artifacts.

This is the wave-3 seed of docs/new_gen/02-plugin-data-contract.md stage 2: the
generator that turns a single declaration file (contract/plugins/<plugin>.decl.json,
itself TRANSCRIBED from today's hand-written headers) into

    <plugin>_keys.gen.h    the key-constants contract (guard 1) — same namespace,
                           constant NAMES + VALUES + kSchemaVersion as the
                           hand-written <plugin>_keys.h (formatting may differ).
    <plugin>.gen.ts        TypeScript interfaces over the JSON-carried keys.
    <plugin>_gen.py        Python TypedDicts over the JSON-carried keys.
    <plugin>_keys.md       a docs keys-table fragment.

The <plugin>_io.gen.h (typed xi::Record I/O views) and <plugin>_schema.gen.h
(xi_record_schema keysets) halves were RETIRED at THE CUT (v12) together with
xi::Record itself; only the ABI-neutral key constants remain generated.

It EXTENDS contract/codegen/gen_types.py (the run-outcome TS/Py probe): same
BANNER discipline, same scalar type maps, deterministic output (declaration
order, no timestamps) so a regenerate is a no-op diff.

    python contract/codegen/gen_contract.py                 # -> generated/plugins/
    python contract/codegen/gen_contract.py --out <dir>     # regenerate elsewhere
    python contract/codegen/gen_contract.py --check         # regen to a tmp dir,
                                                            # diff vs committed (stale?)

The equivalence proof that these are a DROP-IN for the hand-written headers is
contract/codegen/check_equiv.py (the codegen_equiv ctest); see
contract/codegen/README.md.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONTRACT = HERE.parent
DECLS = CONTRACT / "plugins"
DEFAULT_OUT = HERE / "generated" / "plugins"


# ---- naming (deterministic, matches the hand-written convention) ------------

def k_name(key: str) -> str:
    """Record key -> its `k`-prefixed C++ constant name (min_area -> kMinArea)."""
    return "k" + "".join(w[:1].upper() + w[1:] for w in key.split("_"))


def pascal(name: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in name.replace("-", "_").split("_"))


# int/double/bool/string map to the same C++/TS/Py the probe uses; `image` is
# special (it rides the Record image bag, not the JSON) and is handled inline.
CPP_SCALAR = {"int": "int", "double": "double", "bool": "bool", "string": "std::string"}
CONTRACT_TYPE = {"int": "Int", "double": "Double", "bool": "Bool",
                 "string": "String", "image": "Image"}
TS_SCALAR = {"int": "number", "double": "number", "bool": "boolean", "string": "string"}
PY_SCALAR = {"int": "int", "double": "float", "bool": "bool", "string": "str"}

# Reply fields (exchange() reply strings) are still DECLARED and validated —
# their keys ride _keys.gen.h — but the typed reply extractors went with
# _io.gen.h at THE CUT (v12).
REPLY_GETTER = {"int": ("int", "as_int"), "double": ("double", "as_double"),
                "bool": ("bool", "as_bool"), "string": ("std::string", "as_string")}
# A reply field may declare ONE whitelisted C++ cast over its as_* read (the
# constrained escape hatch for config_swap_probe's double-carried counter read
# back as `long long`). Growing this set is a deliberate generator change, not
# open templating.
REPLY_CASTS = {"long long"}


def banner(decl_name: str, comment: str = "//") -> str:
    return (f"{comment} GENERATED by contract/codegen/gen_contract.py from "
            f"contract/plugins/{decl_name}.decl.json — DO NOT EDIT.")


# ---- key collection ---------------------------------------------------------

def _walk_fields(fields, out):
    """Depth-first collect (key, doc) from a field list, recursing arrays."""
    for f in fields:
        out.append((f["key"], f.get("doc", "")))
        if f.get("type") == "array":
            _walk_fields(f.get("fields", []), out)


def collect_keys(decl: dict) -> list[tuple[str, str]]:
    """Every (key, doc) the _keys.h defines, in declaration order, de-duplicated.

    Mirrors exactly the constant set the hand-written header lists so the drift
    check (check_equiv.py) compares like for like."""
    ordered: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(key: str, doc: str = ""):
        if key not in seen:
            seen.add(key)
            ordered.append((key, doc))

    for inp in decl.get("inputs", []):
        add(inp["key"], inp.get("doc", ""))
        if inp.get("type") == "array":
            tmp: list[tuple[str, str]] = []
            _walk_fields(inp.get("fields", []), tmp)
            for k, d in tmp:
                add(k, d)
    for out in decl.get("outputs", []):
        add(out["key"], out.get("doc", ""))
        if out.get("type") == "array":
            tmp = []
            _walk_fields(out.get("fields", []), tmp)
            for k, d in tmp:
                add(k, d)
    for rep in decl.get("replies", []):
        for f in rep.get("fields", []):
            add(f["key"], f.get("doc", ""))
    for cfg in decl.get("config", []):
        add(cfg["key"], cfg.get("doc", ""))
    cmds = decl.get("commands")
    if cmds:
        add(cmds["selector_key"], "string (command selector)")
        add(cmds["value_key"], "int (command payload value)")
        for c in cmds["list"]:
            add(c["name"], "")  # the command name is itself a key constant
            for p in c.get("params", []):
                add(p["key"], "")
    for fr in decl.get("output_frame", []):
        add(fr["key"], fr.get("doc", ""))
    return ordered


def _walk_field_types(fields, out):
    for f in fields:
        out[f["key"]] = f.get("type", "")
        if f.get("type") == "array":
            _walk_field_types(f.get("fields", []), out)


def key_type_map(decl: dict) -> dict[str, str]:
    """key -> declared type label, for the docs table (same coverage as collect_keys)."""
    t: dict[str, str] = {}
    for inp in decl.get("inputs", []):
        t[inp["key"]] = inp.get("type", "")
        if inp.get("type") == "array":
            _walk_field_types(inp.get("fields", []), t)
    for out in decl.get("outputs", []):
        t[out["key"]] = out.get("type", "")
        if out.get("type") == "array":
            _walk_field_types(out.get("fields", []), t)
    for rep in decl.get("replies", []):
        for f in rep.get("fields", []):
            t.setdefault(f["key"], f.get("type", ""))
    for cfg in decl.get("config", []):
        t[cfg["key"]] = cfg.get("type", "")
    cmds = decl.get("commands")
    if cmds:
        t.setdefault(cmds["selector_key"], "string")
        t.setdefault(cmds["value_key"], "int")
        for c in cmds["list"]:
            t.setdefault(c["name"], "string (command name)")
            for p in c.get("params", []):
                t[p["key"]] = p.get("type", "")
    for fr in decl.get("output_frame", []):
        t[fr["key"]] = fr.get("type", "")
    return t


# ---- <plugin>_keys.gen.h ----------------------------------------------------

def gen_keys(decl: dict) -> str:
    ns = decl["namespace"]
    L = [
        "#pragma once",
        banner(decl["plugin"]),
        f"// {decl.get('title', decl['plugin'])}",
        "//",
        "// The single source of truth for this plugin's Record key names (guard 1 of",
        "// the plugin data contract). Every string key is named exactly once; the",
        "// builder, the extractor, and the plugin's own reader all compile from it.",
        "// kSchemaVersion bumps on an incompatible input/config change.",
        "",
        f"namespace {ns} {{",
        "",
        f"inline constexpr int kSchemaVersion = {decl['schema_version']};",
        "",
        "namespace keys {",
        "",
    ]
    for key, doc in collect_keys(decl):
        line = f'inline constexpr const char* {k_name(key)} = "{key}";'
        if doc:
            line += f"  // {doc}"
        L.append(line)
    L += ["", "}  // namespace keys", f"}}  // namespace {ns}", ""]
    return "\n".join(L)


# The _schema.gen.h (PackSchema CRTP keyset) and _io.gen.h (typed Record I/O
# view) generators lived here until THE CUT (v12): xi::Record and
# xi_record_schema.hpp left the SDK, so those artifact halves are retired.
# Only the ABI-neutral _keys.gen.h (+ TS/Py/docs) halves remain.


# ---- TS + Py (extends gen_types.py patterns) --------------------------------

def _json_fields(fields):
    """Yield (key, type, nested_fields|None) for JSON-carried (non-image) fields."""
    for f in fields:
        if f["type"] == "image":
            continue
        yield f["key"], f["type"], (f.get("fields") if f["type"] == "array" else None)


def _ts_interfaces(root_name: str, fields: list, acc: dict) -> None:
    """Populate acc[name] = [lines] for root + nested array-item interfaces."""
    body = []
    for key, typ, nested in _json_fields(fields):
        if typ == "array":
            item_name = root_name + pascal(fields_lookup_class(fields, key))
            _ts_interfaces(item_name, nested, acc)
            body.append(f"  {key}?: {item_name}[];")
        else:
            body.append(f"  {key}?: {TS_SCALAR[typ]};")
    acc[root_name] = [f"export interface {root_name} {{", *body, "}"]


def fields_lookup_class(fields, key):
    for f in fields:
        if f["key"] == key:
            return f.get("item_class", pascal(key))
    return pascal(key)


def gen_ts(decl: dict) -> str:
    root = pascal(decl["plugin"])
    L = [banner(decl["plugin"]),
         "// TypeScript view over the JSON-carried keys (images ride the Record image",
         "// bag, not the JSON, so they are omitted here). Source of truth is the decl.",
         ""]
    acc: dict[str, list[str]] = {}
    order: list[str] = []
    if decl["role"] == "operator":
        _ts_interfaces(root + "Input", decl.get("inputs", []), acc)
        order.append(root + "Input")
        _ts_interfaces(root + "Output", decl.get("outputs", []), acc)
        order.append(root + "Output")
    else:
        _ts_interfaces(root + "Config", decl.get("config", []), acc)
        order.append(root + "Config")
    # emit nested (array-item) interfaces before the roots that reference them
    emitted = set()

    def emit(name):
        if name in emitted:
            return
        emitted.add(name)
        L.extend(acc[name])
        L.append("")
    for name in list(acc.keys()):
        if name not in order:
            emit(name)
    for name in order:
        emit(name)
    return "\n".join(L)


def _py_typeddicts(root_name: str, fields: list, out_lines: list, order: list) -> None:
    body = []
    nested_first = []
    for key, typ, nested in _json_fields(fields):
        if typ == "array":
            item_name = root_name + pascal(fields_lookup_class(fields, key))
            _py_typeddicts(item_name, nested, nested_first, order)
            body.append(f'    {json.dumps(key)}: NotRequired[List[{item_name}]],')
        else:
            body.append(f'    {json.dumps(key)}: NotRequired[{PY_SCALAR[typ]}],')
    out_lines.extend(nested_first)
    out_lines.append(f"{root_name} = TypedDict('{root_name}', {{")
    out_lines.extend(body)
    out_lines.append("})")
    out_lines.append("")
    order.append(root_name)


def gen_py(decl: dict) -> str:
    root = pascal(decl["plugin"])
    L = [banner(decl["plugin"], "#"),
         "# Python view over the JSON-carried keys (images omitted — they ride the",
         "# Record image bag, not the JSON). Source of truth is the decl.",
         "from __future__ import annotations",
         "from typing import TypedDict, NotRequired, List",
         ""]
    order: list[str] = []
    if decl["role"] == "operator":
        _py_typeddicts(root + "Input", decl.get("inputs", []), L, order)
        _py_typeddicts(root + "Output", decl.get("outputs", []), L, order)
    else:
        _py_typeddicts(root + "Config", decl.get("config", []), L, order)
    return "\n".join(L)


# ---- docs keys-table fragment ----------------------------------------------

def gen_keys_md(decl: dict) -> str:
    types = key_type_map(decl)
    L = [f"<!-- GENERATED by contract/codegen/gen_contract.py from "
         f"contract/plugins/{decl['plugin']}.decl.json -- DO NOT EDIT. -->",
         f"### `{decl['plugin']}` keys (schema v{decl['schema_version']}, role: {decl['role']})",
         "",
         "| key | constant | type | notes |",
         "|---|---|---|---|"]
    for key, doc in collect_keys(decl):
        L.append(f"| `{key}` | `{k_name(key)}` | {types.get(key, '')} | {doc} |")
    L.append("")
    return "\n".join(L)


# ---- driver -----------------------------------------------------------------

# "_io.gen.h" and "_schema.gen.h" were retired at THE CUT (v12) with xi::Record.
ARTIFACTS = {
    "_keys.gen.h": gen_keys,
    ".gen.ts": gen_ts,
    "_gen.py": gen_py,
    "_keys.md": gen_keys_md,
}


_IDENT = re.compile(r"^[A-Za-z_]\w*$")


def _validate_decl(decl: dict) -> None:
    """The decl-subset validator: a decl may only say what the generator can
    faithfully emit (the constrained-subset philosophy — no open templating).
    Unknown sections/attributes are ERRORS, and the bespoke escape hatches
    (raw_json splicing, reply casts, patch_builder) are fixed whitelisted
    shapes. Runs on every load, so gen_contract.py AND check_equiv.py both
    refuse a decl the generator would mis-render."""
    plugin = decl.get("plugin", "?")

    def fail(msg: str):
        raise ValueError(f"decl {plugin}: {msg}")

    def check_attrs(obj: dict, allowed: set, what: str):
        extra = set(obj) - allowed
        if extra:
            fail(f"{what} has unsupported attribute(s) {sorted(extra)} "
                 f"(constrained subset: {sorted(allowed)})")

    def check_ident(name, what: str):
        if not isinstance(name, str) or not _IDENT.match(name):
            fail(f"{what} {name!r} is not a C++ identifier")

    check_attrs(decl, {"$comment", "plugin", "namespace", "schema_version", "role",
                       "title", "handwritten_io", "inputs", "outputs", "config",
                       "commands", "output_frame", "replies", "patch_builder",
                       "frame_composites"}, "decl")
    for req in ("plugin", "namespace", "schema_version", "role"):
        if req not in decl:
            fail(f"missing required attribute {req!r}")
    if decl["role"] not in ("operator", "source"):
        fail(f"role {decl['role']!r} must be operator|source")

    def check_field_list(fields, what: str, scalar_ok: set, arrays_ok: bool):
        for f in fields:
            check_attrs(f, {"key", "type", "doc", "required", "channels", "default",
                            "item_accessor", "size_accessor", "item_class", "fields"},
                        f"{what} field {f.get('key', '?')!r}")
            if f.get("type") == "array":
                if not arrays_ok:
                    fail(f"{what} field {f['key']!r}: arrays not allowed here")
                for a in ("item_accessor", "size_accessor", "item_class"):
                    check_ident(f.get(a), f"{what} {f['key']}.{a}")
                check_field_list(f.get("fields", []), f"{what}.{f['key']}",
                                 scalar_ok, arrays_ok)
            elif f.get("type") not in scalar_ok:
                fail(f"{what} field {f.get('key', '?')!r}: type {f.get('type')!r} "
                     f"not in {sorted(scalar_ok)}")

    scalar_or_image = set(CPP_SCALAR) | {"image"}
    check_field_list(decl.get("inputs", []), "inputs", scalar_or_image, True)
    check_field_list(decl.get("outputs", []), "outputs", scalar_or_image, True)
    for fr in decl.get("output_frame", []):
        check_attrs(fr, {"key", "type", "doc", "accessor", "has_accessor"},
                    f"output_frame field {fr.get('key', '?')!r}")
        if fr.get("type") not in scalar_or_image:
            fail(f"output_frame field {fr.get('key', '?')!r}: "
                 f"type {fr.get('type')!r} not in {sorted(scalar_or_image)}")
        for a in ("accessor", "has_accessor"):
            if a in fr:
                check_ident(fr[a], f"output_frame {fr['key']}.{a}")

    for cfg in decl.get("config", []):
        check_attrs(cfg, {"key", "type", "doc", "readonly", "raw_json", "default"},
                    f"config field {cfg.get('key', '?')!r}")
        if cfg.get("type") not in CPP_SCALAR:
            fail(f"config field {cfg.get('key', '?')!r}: type {cfg.get('type')!r}")
        if cfg.get("raw_json") and cfg["type"] != "string":
            fail(f"config field {cfg['key']!r}: raw_json requires type string")
        if "default" in cfg and not cfg.get("raw_json"):
            fail(f"config field {cfg['key']!r}: default is only emitted for "
                 f"raw_json fields (typed setters have no backing member)")

    cmds = decl.get("commands")
    cmd_names = set()
    if cmds:
        check_attrs(cmds, {"selector_key", "value_key", "list"}, "commands")
        for c in cmds.get("list", []):
            check_attrs(c, {"name", "doc", "params"}, f"command {c.get('name', '?')!r}")
            check_ident(c.get("name"), "command name")
            cmd_names.add(c["name"])
            params = c.get("params", [])
            for p in params:
                check_attrs(p, {"key", "arg", "type", "default", "raw_json"},
                            f"command {c['name']} param {p.get('key', '?')!r}")
                check_ident(p.get("arg"), f"command {c['name']} param arg")
                if p.get("type") not in CPP_SCALAR:
                    fail(f"command {c['name']} param {p.get('key', '?')!r}: "
                         f"type {p.get('type')!r}")
                if p.get("raw_json"):
                    if p["type"] != "string":
                        fail(f"command {c['name']}: raw_json param requires type string")
                    if len(params) != 1:
                        fail(f"command {c['name']}: a raw_json param must be the "
                             f"ONLY param (fixed splice shape)")
                    if "default" in p:
                        fail(f"command {c['name']}: raw_json param cannot default")
                elif "default" in p:
                    want = {"int": int, "double": (int, float), "bool": bool,
                            "string": str}[p["type"]]
                    if isinstance(p["default"], bool) and p["type"] != "bool":
                        fail(f"command {c['name']} param {p['key']!r}: bool default "
                             f"on a {p['type']} param")
                    if not isinstance(p["default"], want):
                        fail(f"command {c['name']} param {p['key']!r}: default "
                             f"{p['default']!r} does not match type {p['type']}")

    if decl.get("replies") and decl["role"] != "source":
        fail("replies are a source-role family (exchange() replies)")
    for rep in decl.get("replies", []):
        check_attrs(rep, {"class", "of_command", "doc", "fields"},
                    f"reply {rep.get('class', '?')!r}")
        check_ident(rep.get("class"), "reply class")
        if rep.get("of_command") and rep["of_command"] not in cmd_names:
            fail(f"reply {rep['class']}: of_command {rep['of_command']!r} is not "
                 f"a declared command")
        for f in rep.get("fields", []):
            check_attrs(f, {"key", "type", "doc", "accessor", "cast"},
                        f"reply {rep['class']} field {f.get('key', '?')!r}")
            if f.get("type") not in REPLY_GETTER:
                fail(f"reply {rep['class']} field {f.get('key', '?')!r}: "
                     f"type {f.get('type')!r} not in {sorted(REPLY_GETTER)}")
            if "accessor" in f:
                check_ident(f["accessor"], f"reply {rep['class']} accessor")
            if "cast" in f:
                if f["cast"] not in REPLY_CASTS:
                    fail(f"reply {rep['class']} field {f['key']!r}: cast "
                         f"{f['cast']!r} not whitelisted ({sorted(REPLY_CASTS)})")
                if f["type"] != "double":
                    fail(f"reply {rep['class']} field {f['key']!r}: cast is only "
                         f"defined over the double (number) read")

    minted = {k for k, _ in collect_keys(decl)}
    pb = decl.get("patch_builder")
    if pb:
        if decl["role"] != "source":
            fail("patch_builder is a source-role family (process() input)")
        check_attrs(pb, {"class", "doc", "path_key", "value_key", "list_key",
                         "single_accessor", "batch_accessor"}, "patch_builder")
        check_ident(pb.get("class"), "patch_builder class")
        for a in ("path_key", "value_key", "list_key"):
            if pb.get(a) not in minted:
                fail(f"patch_builder.{a} {pb.get(a)!r} is not a declared key "
                     f"(mint it under inputs/commands so _keys.gen.h carries it)")

    if decl.get("frame_composites"):
        image_has = {fr["key"] for fr in decl.get("output_frame", [])
                     if fr.get("type") == "image"}
        for comp in decl["frame_composites"]:
            check_attrs(comp, {"accessor", "all_of", "doc"},
                        f"frame_composite {comp.get('accessor', '?')!r}")
            check_ident(comp.get("accessor"), "frame_composite accessor")
            if not comp.get("all_of"):
                fail(f"frame_composite {comp['accessor']}: all_of must be non-empty")
            for k in comp["all_of"]:
                if k not in image_has:
                    fail(f"frame_composite {comp['accessor']}: {k!r} is not a "
                         f"declared output_frame image key")


def load_decls() -> list[dict]:
    decls = []
    for p in sorted(DECLS.glob("*.decl.json")):
        decl = json.loads(p.read_text(encoding="utf-8"))
        _validate_decl(decl)
        decls.append(decl)
    return decls


def render(decl: dict) -> dict[str, str]:
    """{filename: content} for one decl. Deterministic. (The conditional
    `_io.gen.h`/`_schema.gen.h` skip logic — `handwritten_io`, empty frame
    slots — retired with those artifacts at THE CUT, v12.)"""
    plugin = decl["plugin"]
    return {plugin + suffix: fn(decl) for suffix, fn in ARTIFACTS.items()}


def generate(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for decl in load_decls():
        for name, content in render(decl).items():
            path = out_dir / name
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written


def check(out_dir: Path) -> int:
    """Regenerate into a tmp dir, diff against the committed out_dir. Non-zero if
    any committed artifact is stale (the generator is not deterministic-idempotent
    against what is committed)."""
    import tempfile
    stale = []
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        generate(tmp)
        for fresh in sorted(tmp.iterdir()):
            committed = out_dir / fresh.name
            if not committed.exists():
                stale.append(f"{fresh.name} (missing from {out_dir})")
            elif committed.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                stale.append(f"{fresh.name} (differs from committed)")
    if stale:
        print("codegen STALE — regenerate with `python contract/codegen/gen_contract.py`:")
        for s in stale:
            print(f"  - {s}")
        return 1
    print(f"codegen: committed artifacts in {out_dir} are up to date")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help="output directory (default: contract/codegen/generated/plugins)")
    ap.add_argument("--check", action="store_true",
                    help="verify committed artifacts are up to date (no write)")
    args = ap.parse_args()
    if args.check:
        return check(args.out)
    written = generate(args.out)
    print(f"codegen: wrote {len(written)} artifact(s) for "
          f"{len(load_decls())} plugin(s) to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
