#!/usr/bin/env python3
"""Codegen PROBE — emit TypeScript + Python types from a contract schema.

Scope: the smallest useful slice — the xi.run-outcome/1 payload
(contract/schemas/run-outcome.schema.json). This is a PROBE, not the real
generator: it handles exactly the subset the contract schemas use (object with
scalar/enum/const/array properties, required vs optional, local $defs $ref) and
nothing more. Its job is to answer 'does the constrained subset generate clean,
compiling types on both target languages?' — see docs/new_gen/05-schema-language-spike.md.

    python contract/codegen/gen_types.py

Regenerates contract/codegen/generated/run_outcome.generated.{ts,py}. The
generated files are committed (clearly marked) so a reviewer sees the output
without running the tool.
"""
from __future__ import annotations

import json
from pathlib import Path

CONTRACT = Path(__file__).resolve().parents[1]
OUT = Path(__file__).resolve().parent / "generated"
SCHEMA = CONTRACT / "schemas" / "run-outcome.schema.json"
ROOT_NAME = "RunOutcome"

BANNER = "// GENERATED by contract/codegen/gen_types.py from schemas/run-outcome.schema.json — DO NOT EDIT."
BANNER_PY = "# GENERATED by contract/codegen/gen_types.py from schemas/run-outcome.schema.json — DO NOT EDIT."


def ts_type(node: dict) -> str:
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    t = node.get("type")
    if isinstance(t, list):
        return " | ".join(ts_type({"type": x}) for x in t)
    if t == "integer" or t == "number":
        return "number"
    if t == "string":
        return "string"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        return f"{ts_type(node.get('items', {}))}[]"
    if t == "object":
        return "Record<string, unknown>"
    return "unknown"


def py_type(node: dict) -> str:
    if "const" in node:
        return f"Literal[{json.dumps(node['const'])}]"
    if "enum" in node:
        return "Literal[" + ", ".join(json.dumps(v) for v in node["enum"]) + "]"
    t = node.get("type")
    if isinstance(t, list):
        return "Union[" + ", ".join(py_type({"type": x}) for x in t) + "]"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "string":
        return "str"
    if t == "boolean":
        return "bool"
    if t == "null":
        return "None"
    if t == "array":
        return f"List[{py_type(node.get('items', {}))}]"
    if t == "object":
        return "Dict[str, object]"
    return "object"


def gen_ts(schema: dict) -> str:
    props = schema["properties"]
    required = set(schema.get("required", []))
    lines = [
        BANNER,
        "// Source of truth is the schema; this file is a generated VIEW. Wire keys are",
        "// verbatim (including the reserved-word `class`); an ergonomic rename layer is",
        "// the consumer's, not the generator's (cf. vscode-extension/src/runOutcome.ts).",
        "",
        f"export interface {ROOT_NAME} {{",
    ]
    for key, node in props.items():
        opt = "" if key in required else "?"
        desc = node.get("description", "")
        if desc:
            lines.append(f"  /** {desc.splitlines()[0]} */")
        prop = key if key.isidentifier() else json.dumps(key)
        lines.append(f"  {prop}{opt}: {ts_type(node)};")
    # additive-only wire: allow unknown keys, mirroring additionalProperties:true.
    if schema.get("additionalProperties", False) is True:
        lines.append("  [k: string]: unknown; // additionalProperties:true (additive-only wire)")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def gen_py(schema: dict) -> str:
    props = schema["properties"]
    required = set(schema.get("required", []))
    lines = [
        BANNER_PY,
        "# Functional TypedDict form because a wire key (`class`) is a Python keyword;",
        "# Required/NotRequired (PEP 655, stdlib since 3.11) carry the required flag.",
        "from __future__ import annotations",
        "from typing import TypedDict, Literal, Required, NotRequired, List, Dict, Union",
        "",
        f"{ROOT_NAME} = TypedDict('{ROOT_NAME}', {{",
    ]
    for key, node in props.items():
        wrap = "Required" if key in required else "NotRequired"
        lines.append(f"    {json.dumps(key)}: {wrap}[{py_type(node)}],")
    lines.append("})")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "run_outcome.generated.ts").write_text(gen_ts(schema), encoding="utf-8")
    (OUT / "run_outcome.generated.py").write_text(gen_py(schema), encoding="utf-8")
    print(f"codegen: wrote {ROOT_NAME} TS + Py to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
