#!/usr/bin/env python3
"""Contract codegen — ONE plugin declaration -> the generated view artifacts.

This is the wave-3 seed of docs/new_gen/02-plugin-data-contract.md stage 2: the
generator that turns a single declaration file (contract/plugins/<plugin>.decl.json,
itself TRANSCRIBED from today's hand-written headers) into

    <plugin>_keys.gen.h    the key-constants contract (guard 1) — same namespace,
                           constant NAMES + VALUES + kSchemaVersion as the
                           hand-written <plugin>_keys.h (formatting may differ).
    <plugin>_schema.gen.h  the FrameSchema<Derived> CRTP keyset (enum slots +
                           keys array) for the offset-accessor frame path.
    <plugin>_io.gen.h      the Input/Output (operator) or Config/Command/Frame
                           (source) builder+extractor classes — byte-for-byte the
                           call surface the plugin's .cpp and tests already use.
    <plugin>.gen.ts        TypeScript interfaces over the JSON-carried keys.
    <plugin>_gen.py        Python TypedDicts over the JSON-carried keys.
    <plugin>_keys.md       a docs keys-table fragment.

It EXTENDS contract/codegen/gen_types.py (the run-outcome TS/Py probe): same
BANNER discipline, same scalar type maps, deterministic output (declaration
order, no timestamps) so a regenerate is a no-op diff.

    python contract/codegen/gen_contract.py                 # -> generated/plugins/
    python contract/codegen/gen_contract.py --out <dir>     # regenerate elsewhere
    python contract/codegen/gen_contract.py --check         # regen to a tmp dir,
                                                            # diff vs committed (stale?)

The equivalence proof that these are a DROP-IN for the hand-written headers is
contract/codegen/check_equiv.py (the codegen_equiv ctest) + the compiled
codegen_equiv_test TU; see contract/codegen/README.md.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CONTRACT = HERE.parent
DECLS = CONTRACT / "plugins"
DEFAULT_OUT = HERE / "generated" / "plugins"


# ---- naming (deterministic, matches the hand-written convention) ------------

def k_name(key: str) -> str:
    """Record key -> its `k`-prefixed C++ constant name (min_area -> kMinArea)."""
    return "k" + "".join(w[:1].upper() + w[1:] for w in key.split("_"))


def pascal(name: str) -> str:
    return "".join(w[:1].upper() + w[1:] for w in name.replace("-", "_").split("_"))


# int/double/bool/string map to the same C++/TS/Py the probe uses; `image` is
# special (it rides the Record image bag, not the JSON) and is handled inline.
CPP_SCALAR = {"int": "int", "double": "double", "bool": "bool", "string": "std::string"}
CONTRACT_TYPE = {"int": "Int", "double": "Double", "bool": "Bool",
                 "string": "String", "image": "Image"}
GETTER = {"int": "get_int", "double": "get_double", "bool": "get_bool",
          "string": "get_string"}
TS_SCALAR = {"int": "number", "double": "number", "bool": "boolean", "string": "string"}
PY_SCALAR = {"int": "int", "double": "float", "bool": "bool", "string": "str"}


def banner(decl_name: str, comment: str = "//") -> str:
    return (f"{comment} GENERATED by contract/codegen/gen_contract.py from "
            f"contract/plugins/{decl_name}.decl.json — DO NOT EDIT.")


# ---- key collection ---------------------------------------------------------

def _walk_fields(fields, out):
    """Depth-first collect (key, doc) from a field list, recursing arrays."""
    for f in fields:
        out.append((f["key"], f.get("doc", "")))
        if f.get("type") == "array":
            _walk_fields(f.get("fields", []), out)


def collect_keys(decl: dict) -> list[tuple[str, str]]:
    """Every (key, doc) the _keys.h defines, in declaration order, de-duplicated.

    Mirrors exactly the constant set the hand-written header lists so the drift
    check (check_equiv.py) compares like for like."""
    ordered: list[tuple[str, str]] = []
    seen: set[str] = set()

    def add(key: str, doc: str = ""):
        if key not in seen:
            seen.add(key)
            ordered.append((key, doc))

    for inp in decl.get("inputs", []):
        add(inp["key"], inp.get("doc", ""))
        if inp.get("type") == "array":
            tmp: list[tuple[str, str]] = []
            _walk_fields(inp.get("fields", []), tmp)
            for k, d in tmp:
                add(k, d)
    for out in decl.get("outputs", []):
        add(out["key"], out.get("doc", ""))
        if out.get("type") == "array":
            tmp = []
            _walk_fields(out.get("fields", []), tmp)
            for k, d in tmp:
                add(k, d)
    for cfg in decl.get("config", []):
        add(cfg["key"], cfg.get("doc", ""))
    cmds = decl.get("commands")
    if cmds:
        add(cmds["selector_key"], "string (command selector)")
        add(cmds["value_key"], "int (command payload value)")
        for c in cmds["list"]:
            add(c["name"], "")  # the command name is itself a key constant
            for p in c.get("params", []):
                add(p["key"], "")
    for fr in decl.get("output_frame", []):
        add(fr["key"], fr.get("doc", ""))
    return ordered


def _walk_field_types(fields, out):
    for f in fields:
        out[f["key"]] = f.get("type", "")
        if f.get("type") == "array":
            _walk_field_types(f.get("fields", []), out)


def key_type_map(decl: dict) -> dict[str, str]:
    """key -> declared type label, for the docs table (same coverage as collect_keys)."""
    t: dict[str, str] = {}
    for inp in decl.get("inputs", []):
        t[inp["key"]] = inp.get("type", "")
        if inp.get("type") == "array":
            _walk_field_types(inp.get("fields", []), t)
    for out in decl.get("outputs", []):
        t[out["key"]] = out.get("type", "")
        if out.get("type") == "array":
            _walk_field_types(out.get("fields", []), t)
    for cfg in decl.get("config", []):
        t[cfg["key"]] = cfg.get("type", "")
    cmds = decl.get("commands")
    if cmds:
        t.setdefault(cmds["selector_key"], "string")
        t.setdefault(cmds["value_key"], "int")
        for c in cmds["list"]:
            t.setdefault(c["name"], "string (command name)")
            for p in c.get("params", []):
                t[p["key"]] = p.get("type", "")
    for fr in decl.get("output_frame", []):
        t[fr["key"]] = fr.get("type", "")
    return t


# ---- <plugin>_keys.gen.h ----------------------------------------------------

def gen_keys(decl: dict) -> str:
    ns = decl["namespace"]
    L = [
        "#pragma once",
        banner(decl["plugin"]),
        f"// {decl.get('title', decl['plugin'])}",
        "//",
        "// The single source of truth for this plugin's Record key names (guard 1 of",
        "// the plugin data contract). Every string key is named exactly once; the",
        "// builder, the extractor, and the plugin's own reader all compile from it.",
        "// kSchemaVersion bumps on an incompatible input/config change.",
        "",
        f"namespace {ns} {{",
        "",
        f"inline constexpr int kSchemaVersion = {decl['schema_version']};",
        "",
        "namespace keys {",
        "",
    ]
    for key, doc in collect_keys(decl):
        line = f'inline constexpr const char* {k_name(key)} = "{key}";'
        if doc:
            line += f"  // {doc}"
        L.append(line)
    L += ["", "}  // namespace keys", f"}}  // namespace {ns}", ""]
    return "\n".join(L)


# ---- <plugin>_schema.gen.h (FrameSchema CRTP keyset) ------------------------

def frame_slot_keys(decl: dict) -> list[str]:
    """The flat, top-level keys that become FrameSchema slots (the offset-accessor
    frame path). Arrays are NOT slots (they ride as dynamic/Mp entries), so they
    are skipped. operator: inputs + non-array outputs; source: the output frame."""
    keys: list[str] = []
    if decl["role"] == "operator":
        for inp in decl.get("inputs", []):
            keys.append(inp["key"])
        for out in decl.get("outputs", []):
            if out.get("type") != "array":
                keys.append(out["key"])
    else:  # source
        for fr in decl.get("output_frame", []):
            keys.append(fr["key"])
    # de-dup preserving order
    seen, uniq = set(), []
    for k in keys:
        if k not in seen:
            seen.add(k)
            uniq.append(k)
    return uniq


def gen_schema(decl: dict) -> str:
    ns = decl["namespace"]
    cls = pascal(decl["plugin"]) + "Schema"
    slot_keys = frame_slot_keys(decl)
    n = len(slot_keys)
    keys_lit = ", ".join(f'"{k}"' for k in slot_keys)
    enum_lit = ", ".join(k_name(k) for k in slot_keys)
    L = [
        "#pragma once",
        banner(decl["plugin"]),
        f"// FrameSchema keyset for {decl['plugin']} — the compile-time declared key",
        "// order the offset-accessor read path resolves to slots (docs/new_gen/07).",
        "// enum names ARE the slots; TypedFrame<Schema> reads slots_[kX] directly —",
        "// no hash, no scan. Arrays are omitted (they are not flat slots).",
        "",
        "#include <xi/xi_frame.hpp>",
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        f"namespace {ns} {{",
        "",
        f"struct {cls} : xi::FrameSchema<{cls}> {{",
        f"    static constexpr std::array<std::string_view, {n}> keys = {{ {keys_lit} }};",
        f"    enum : int {{ {enum_lit} }};",
        "};",
        "",
        f"}}  // namespace {ns}",
        "",
    ]
    return "\n".join(L)


# ---- <plugin>_io.gen.h ------------------------------------------------------

def _output_getter(key: str, typ: str, indent: str) -> str:
    if typ == "image":
        return (f"{indent}const xi::Image& {key}() const "
                f"{{ return rec_.get_image(keys::{k_name(key)}); }}")
    g = GETTER[typ]
    ret = CPP_SCALAR[typ]
    return f"{indent}{ret} {key}() const {{ return rec_.{g}(keys::{k_name(key)}); }}"


def _emit_extractor_class(field: dict, indent: str, lines: list[str]) -> None:
    """Emit a nested extractor class for an array-of-object output field."""
    cls = field["item_class"]
    lines.append(f"{indent}class {cls} {{")
    lines.append(f"{indent}public:")
    lines.append(f"{indent}    explicit {cls}(xi::Record r) : r_(std::move(r)) {{}}")
    for sub in field["fields"]:
        st = sub["type"]
        if st == "array":
            lines.append("")
            # recurse: nested class, then size()/item(i)
            nested: list[str] = []
            _emit_extractor_class(sub, indent + "    ", nested)
            lines.extend(nested)
            sz, item, icls = sub["size_accessor"], sub["item_accessor"], sub["item_class"]
            lines.append(f"{indent}    int {sz}() const "
                         f"{{ return r_.get_array_size(keys::{k_name(sub['key'])}); }}")
            lines.append(f"{indent}    {icls} {item}(int i) const "
                         f"{{ return {icls}(r_.get_array_item(keys::{k_name(sub['key'])}, i)); }}")
        else:
            g, ret = GETTER[st], CPP_SCALAR[st]
            lines.append(f"{indent}    {ret} {sub['key']}() const "
                         f"{{ return r_.{g}(keys::{k_name(sub['key'])}); }}")
    lines.append(f"{indent}private:")
    lines.append(f"{indent}    xi::Record r_;")
    lines.append(f"{indent}}};")


def gen_io_operator(decl: dict) -> str:
    ns = decl["namespace"]
    L = [
        "#pragma once",
        banner(decl["plugin"]),
        f"// Typed view over {decl['plugin']}'s Record I/O (stage-1 deliverable, now",
        "// GENERATED). Input builder + Output extractor compile straight down to",
        "// xi::Record set/get over the _keys.gen.h constants — nothing new crosses",
        "// the ABI, a key typo is a compile error.",
        "",
        f'#include "{decl["plugin"]}_keys.gen.h"',
        "",
        "#include <xi/xi_contract.hpp>",
        "#include <xi/xi_record.hpp>",
        "",
        f"namespace {ns} {{",
        "",
        "// ---- Input builder --------------------------------------------------------",
        "class Input {",
        "public:",
        "    Input() { rec_.set(xi::contract::kSchemaKey, kSchemaVersion); }",
        "",
    ]
    for inp in decl.get("inputs", []):
        key, typ = inp["key"], inp["type"]
        if typ == "image":
            L.append(f"    Input& {key}(xi::Image img) "
                     f"{{ rec_.image(keys::{k_name(key)}, std::move(img)); return *this; }}")
        else:
            arg = CPP_SCALAR[typ]
            L.append(f"    Input& {key}({arg} v) "
                     f"{{ rec_.set(keys::{k_name(key)}, v); return *this; }}")
    L += [
        "",
        "    const xi::Record& record() const { return rec_; }",
        "    operator const xi::Record&() const { return rec_; }",
        "",
        "private:",
        "    xi::Record rec_;",
        "};",
        "",
        "// ---- Output extractor -----------------------------------------------------",
        "class Output {",
        "public:",
        "    explicit Output(xi::Record rec) : rec_(std::move(rec)) {}",
        "",
        "    bool ok() const { return !rec_.is_na(); }",
        "    std::string na_reason() const { return rec_.na_reason(); }",
        "    std::string fault_code() const {",
        "        return rec_.get_record(xi::contract::kFaultKey).get_string(xi::contract::kCode);",
        "    }",
        "",
    ]
    # scalar/image outputs first, then array-of-object accessors + nested classes
    for out in decl.get("outputs", []):
        if out.get("type") != "array":
            L.append(_output_getter(out["key"], out["type"], "    "))
    for out in decl.get("outputs", []):
        if out.get("type") == "array":
            L.append("")
            nested: list[str] = []
            _emit_extractor_class(out, "    ", nested)
            L.extend(nested)
            sz, item, icls = out["size_accessor"], out["item_accessor"], out["item_class"]
            L.append(f"    int {sz}() const "
                     f"{{ return rec_.get_array_size(keys::{k_name(out['key'])}); }}")
            L.append(f"    {icls} {item}(int i) const "
                     f"{{ return {icls}(rec_.get_array_item(keys::{k_name(out['key'])}, i)); }}")
    L += [
        "",
        "    const xi::Record& record() const { return rec_; }",
        "",
        "private:",
        "    xi::Record rec_;",
        "};",
        "",
        f"}}  // namespace {ns}",
        "",
    ]
    return "\n".join(L)


def gen_io_source(decl: dict) -> str:
    ns = decl["namespace"]
    L = [
        "#pragma once",
        banner(decl["plugin"]),
        f"// Typed view over {decl['plugin']}'s config, commands, and emitted frame",
        "// (source plugin; GENERATED). Config -> set_def JSON, Command -> exchange",
        "// JSON, Frame reads the emitted output Record. All compile down to plain",
        "// xi::Json / xi::Record ops — nothing new crosses the ABI.",
        "",
        f'#include "{decl["plugin"]}_keys.gen.h"',
        "",
        "#include <xi/xi_contract.hpp>",
        "#include <xi/xi_json.hpp>",
        "#include <xi/xi_record.hpp>",
        "",
        "#include <string>",
        "",
        f"namespace {ns} {{",
        "",
        "// ---- Config builder (produces the set_def JSON) ---------------------------",
        "class Config {",
        "public:",
        "    Config() { j_ = xi::Json::object().set(xi::contract::kSchemaKey, kSchemaVersion); }",
        "",
    ]
    for cfg in decl.get("config", []):
        if cfg.get("readonly"):
            continue
        arg = CPP_SCALAR[cfg["type"]]
        L.append(f"    Config& {cfg['key']}({arg} v) "
                 f"{{ j_.set(keys::{k_name(cfg['key'])}, v); return *this; }}")
    L += [
        "",
        "    std::string dump() const { return j_.dump(); }",
        "    operator std::string() const { return j_.dump(); }",
        "",
        "private:",
        "    xi::Json j_;",
        "};",
        "",
    ]
    cmds = decl.get("commands")
    if cmds:
        sel = k_name(cmds["selector_key"])
        L += [
            "// ---- Command builder (produces the exchange JSON) -------------------------",
            "class Command {",
            "public:",
        ]
        for c in cmds["list"]:
            name = c["name"]
            params = c.get("params", [])
            if not params:
                L.append(f"    static std::string {name}() "
                         f"{{ return cmd_(keys::{k_name(name)}); }}")
            else:
                sig = ", ".join(f"{CPP_SCALAR[p['type']]} {p['arg']}" for p in params)
                body = f"xi::Json::object().set(keys::{sel}, keys::{k_name(name)})"
                for p in params:
                    body += f".set(keys::{k_name(p['key'])}, {p['arg']})"
                L.append(f"    static std::string {name}({sig}) {{")
                L.append(f"        return {body}.dump();")
                L.append("    }")
        L += [
            "",
            "private:",
            "    static std::string cmd_(const char* name) {",
            f"        return xi::Json::object().set(keys::{sel}, name).dump();",
            "    }",
            "};",
            "",
        ]
    frame = decl.get("output_frame", [])
    if frame:
        L += [
            "// ---- Frame extractor (reads an emitted output Record) ---------------------",
            "class Frame {",
            "public:",
            "    explicit Frame(xi::Record rec) : rec_(std::move(rec)) {}",
            "",
        ]
        for fr in frame:
            if fr["type"] == "image":
                has = fr.get("has_accessor", "has_" + fr["key"])
                acc = fr.get("accessor", fr["key"])
                L.append(f"    bool {has}() const "
                         f"{{ return rec_.has_image(keys::{k_name(fr['key'])}); }}")
                L.append(f"    const xi::Image& {acc}() const "
                         f"{{ return rec_.get_image(keys::{k_name(fr['key'])}); }}")
        L += [
            "",
            "    const xi::Record& record() const { return rec_; }",
            "",
            "private:",
            "    xi::Record rec_;",
            "};",
            "",
        ]
    L += [f"}}  // namespace {ns}", ""]
    return "\n".join(L)


def gen_io(decl: dict) -> str:
    return gen_io_operator(decl) if decl["role"] == "operator" else gen_io_source(decl)


# ---- TS + Py (extends gen_types.py patterns) --------------------------------

def _json_fields(fields):
    """Yield (key, type, nested_fields|None) for JSON-carried (non-image) fields."""
    for f in fields:
        if f["type"] == "image":
            continue
        yield f["key"], f["type"], (f.get("fields") if f["type"] == "array" else None)


def _ts_interfaces(root_name: str, fields: list, acc: dict) -> None:
    """Populate acc[name] = [lines] for root + nested array-item interfaces."""
    body = []
    for key, typ, nested in _json_fields(fields):
        if typ == "array":
            item_name = root_name + pascal(fields_lookup_class(fields, key))
            _ts_interfaces(item_name, nested, acc)
            body.append(f"  {key}?: {item_name}[];")
        else:
            body.append(f"  {key}?: {TS_SCALAR[typ]};")
    acc[root_name] = [f"export interface {root_name} {{", *body, "}"]


def fields_lookup_class(fields, key):
    for f in fields:
        if f["key"] == key:
            return f.get("item_class", pascal(key))
    return pascal(key)


def gen_ts(decl: dict) -> str:
    root = pascal(decl["plugin"])
    L = [banner(decl["plugin"]),
         "// TypeScript view over the JSON-carried keys (images ride the Record image",
         "// bag, not the JSON, so they are omitted here). Source of truth is the decl.",
         ""]
    acc: dict[str, list[str]] = {}
    order: list[str] = []
    if decl["role"] == "operator":
        _ts_interfaces(root + "Input", decl.get("inputs", []), acc)
        order.append(root + "Input")
        _ts_interfaces(root + "Output", decl.get("outputs", []), acc)
        order.append(root + "Output")
    else:
        _ts_interfaces(root + "Config", decl.get("config", []), acc)
        order.append(root + "Config")
    # emit nested (array-item) interfaces before the roots that reference them
    emitted = set()

    def emit(name):
        if name in emitted:
            return
        emitted.add(name)
        L.extend(acc[name])
        L.append("")
    for name in list(acc.keys()):
        if name not in order:
            emit(name)
    for name in order:
        emit(name)
    return "\n".join(L)


def _py_typeddicts(root_name: str, fields: list, out_lines: list, order: list) -> None:
    body = []
    nested_first = []
    for key, typ, nested in _json_fields(fields):
        if typ == "array":
            item_name = root_name + pascal(fields_lookup_class(fields, key))
            _py_typeddicts(item_name, nested, nested_first, order)
            body.append(f'    {json.dumps(key)}: NotRequired[List[{item_name}]],')
        else:
            body.append(f'    {json.dumps(key)}: NotRequired[{PY_SCALAR[typ]}],')
    out_lines.extend(nested_first)
    out_lines.append(f"{root_name} = TypedDict('{root_name}', {{")
    out_lines.extend(body)
    out_lines.append("})")
    out_lines.append("")
    order.append(root_name)


def gen_py(decl: dict) -> str:
    root = pascal(decl["plugin"])
    L = [banner(decl["plugin"], "#"),
         "# Python view over the JSON-carried keys (images omitted — they ride the",
         "# Record image bag, not the JSON). Source of truth is the decl.",
         "from __future__ import annotations",
         "from typing import TypedDict, NotRequired, List",
         ""]
    order: list[str] = []
    if decl["role"] == "operator":
        _py_typeddicts(root + "Input", decl.get("inputs", []), L, order)
        _py_typeddicts(root + "Output", decl.get("outputs", []), L, order)
    else:
        _py_typeddicts(root + "Config", decl.get("config", []), L, order)
    return "\n".join(L)


# ---- docs keys-table fragment ----------------------------------------------

def gen_keys_md(decl: dict) -> str:
    types = key_type_map(decl)
    L = [f"<!-- GENERATED by contract/codegen/gen_contract.py from "
         f"contract/plugins/{decl['plugin']}.decl.json -- DO NOT EDIT. -->",
         f"### `{decl['plugin']}` keys (schema v{decl['schema_version']}, role: {decl['role']})",
         "",
         "| key | constant | type | notes |",
         "|---|---|---|---|"]
    for key, doc in collect_keys(decl):
        L.append(f"| `{key}` | `{k_name(key)}` | {types.get(key, '')} | {doc} |")
    L.append("")
    return "\n".join(L)


# ---- driver -----------------------------------------------------------------

ARTIFACTS = {
    "_keys.gen.h": gen_keys,
    "_schema.gen.h": gen_schema,
    "_io.gen.h": gen_io,
    ".gen.ts": gen_ts,
    "_gen.py": gen_py,
    "_keys.md": gen_keys_md,
}


def load_decls() -> list[dict]:
    decls = []
    for p in sorted(DECLS.glob("*.decl.json")):
        decls.append(json.loads(p.read_text(encoding="utf-8")))
    return decls


def render(decl: dict) -> dict[str, str]:
    """{filename: content} for one decl. Deterministic.

    Two artifacts are conditional, so the generator never emits a file that would
    be a lie about what it can express:

      * `_io.gen.h` is SKIPPED when the decl sets `"handwritten_io": true`. Some
        plugins' control surface is outside the constrained typed-field family the
        decl governs (json_source's open-schema raw-JSON builders + Patch shape;
        config_swap_probe's get_status reply extractor; synced_stereo's derived
        has_both()/defaulted fire()). Their `_io.h` stays hand-written — the
        generator owns the KEY contract (guard 1, `_keys.gen.h`) for them but not
        the bespoke I/O veneer. See contract/codegen/README.md (swap-in) and the
        codegen-gap note in docs/new_gen/08.
      * `_schema.gen.h` is SKIPPED when the plugin declares no flat frame slots
        (a source with no `output_frame`): an empty FrameSchema is noise, nothing
        adopts it, and it would never be compiled.
    """
    plugin = decl["plugin"]
    skip: set[str] = set()
    if decl.get("handwritten_io"):
        skip.add("_io.gen.h")
    if not frame_slot_keys(decl):
        skip.add("_schema.gen.h")
    return {plugin + suffix: fn(decl)
            for suffix, fn in ARTIFACTS.items() if suffix not in skip}


def generate(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for decl in load_decls():
        for name, content in render(decl).items():
            path = out_dir / name
            path.write_text(content, encoding="utf-8", newline="\n")
            written.append(path)
    return written


def check(out_dir: Path) -> int:
    """Regenerate into a tmp dir, diff against the committed out_dir. Non-zero if
    any committed artifact is stale (the generator is not deterministic-idempotent
    against what is committed)."""
    import tempfile
    stale = []
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        generate(tmp)
        for fresh in sorted(tmp.iterdir()):
            committed = out_dir / fresh.name
            if not committed.exists():
                stale.append(f"{fresh.name} (missing from {out_dir})")
            elif committed.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                stale.append(f"{fresh.name} (differs from committed)")
    if stale:
        print("codegen STALE — regenerate with `python contract/codegen/gen_contract.py`:")
        for s in stale:
            print(f"  - {s}")
        return 1
    print(f"codegen: committed artifacts in {out_dir} are up to date")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT,
                    help="output directory (default: contract/codegen/generated/plugins)")
    ap.add_argument("--check", action="store_true",
                    help="verify committed artifacts are up to date (no write)")
    args = ap.parse_args()
    if args.check:
        return check(args.out)
    written = generate(args.out)
    print(f"codegen: wrote {len(written)} artifact(s) for "
          f"{len(load_decls())} plugin(s) to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
