// throwing_plugin.cpp — B2 regression fixture.
//
// A plugin whose every operator THROWS. Two distinct boundaries are proven by
// test_plugin_exception:
//
//   * The LIFECYCLE / config exports (set_def/get_def/exchange) are generated by
//     XI_PLUGIN_IMPL, whose per-call trampolines catch each throw IN THE PLUGIN's
//     OWN RUNTIME and return a safe sentinel — a throw never unwinds across those
//     extern "C" exports into the host (which is UB for a prebuilt / cross-CRT
//     plugin).
//
//   * The DATA-PLANE door is the xi.pack@1 door (THE CUT / v12: the Record
//     process() path is gone). It is HAND-WRITTEN here, deliberately NOT via
//     XI_PLUGIN_PACK_DOOR — that macro's trampoline would catch in-plugin. This
//     RAW door lets the throw escape across the extern "C" boundary so the test
//     can prove the HOST boundary (CAbiInstanceAdapter::run_pack_door's caller)
//     is the one that contains it. In this single-toolchain test both sides share
//     the CRT, so the unwind is well-defined and catchable at the host.
#include <xi/xi_abi.hpp>

#include <cstring>
#include <stdexcept>

class ThrowingPlugin : public xi::Plugin {
public:
    using xi::Plugin::Plugin;
    std::string exchange(const std::string&) override { throw std::runtime_error("exchange boom"); }
    std::string get_def() const              override { throw std::runtime_error("get_def boom"); }
    bool        set_def(const std::string&)  override { throw std::runtime_error("set_def boom"); }
};

XI_PLUGIN_IMPL(ThrowingPlugin)

// The RAW xi.pack@1 data-plane door: it throws, and the throw is NOT caught here
// (no XI_PLUGIN_PACK_DOOR trampoline). run_pack_door calls this directly, so the
// C++ exception propagates out to the host's boundary, exactly as the test asserts.
static xi_pack_handle throwing_pack_process(void* /*inst*/, xi_pack_handle /*in*/) {
    throw std::runtime_error("process boom");
}

extern "C" XI_EXPORT
const void* xi_plugin_get_interface(const char* id, uint32_t version) {
    if (id && version == 1u && std::strcmp(id, "xi.pack") == 0) {
        static const xi_pack_proc_v1 iface = { &throwing_pack_process };
        return &iface;
    }
    return nullptr;
}
