#!/usr/bin/env python3
"""check_doc_coverage.py — a freeze guard for developer-facing docs.

WHY THIS EXISTS
---------------
Public surface (the plugin/script C-ABI exports the host resolves, and the WS
commands a client sends) kept shipping while the developer-facing guides lagged
behind — A4's `xi_inspect_entry_tv`, G4's `xi_script_code_change`, OQ-7b's
`xi_plugin_record_schema`, OQ-7a's `cmd:metrics` all landed in code (and only in
INTERNAL residue docs) rounds before anyone updated docs/guides or docs/reference.
Nothing FAILED when that happened, so the lag was only ever caught by manual review.

This is the analogue of test_abi_freeze, but for docs: it derives the public
surface straight from the source of truth (the loader's GetProcAddress strings +
the WS command dispatcher) and asserts every item is documented in a
DEVELOPER-FACING tree (docs/guides + docs/reference). Internal residue
(docs/internals) and docs/archive DELIBERATELY do NOT count as coverage — that is
the exact distinction that would have caught the regressions above.

A symbol that is genuinely internal (SDK plumbing the user never types) is
silenced by listing it in docs/.doc-coverage-allow with a one-line reason — an
EXPLICIT opt-out, never a silent gap.

Run standalone (exits non-zero on a gap):  python tools/check_doc_coverage.py
Also wired as the `doc_coverage` ctest.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XI_INC = ROOT / "backend" / "include" / "xi"
XI_SRC = ROOT / "backend" / "src"
SERVICE_MAIN = XI_SRC / "service_main.cpp"
DOC_ROOTS = [ROOT / "docs" / "guides", ROOT / "docs" / "reference"]
ALLOW_FILE = ROOT / "docs" / ".doc-coverage-allow"

# --- source-of-truth extractors -------------------------------------------

def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")

# The authoring MACROS a plugin/script writer types by hand. Curated (not
# auto-extracted) so the check stays low-noise vs the many internal XI_* macros
# (header guards, test asserts, ABI constants). Each is validated below to still
# be #define'd in a public header, so this list cannot silently go stale.
AUTHORING_MACROS = [
    "XI_INSPECT_ENTRY",   # the A4 explicit-trigger script entry
    "XI_SCRIPT_EXPORT",   # marks the legacy script entry / support exports
    # XI_STATE_SCHEMA left this list at THE CUT (v12, doc 16 item 7):
    # xi_state.hpp was deleted with the Record plane; XI_KV_SCHEMA is the
    # state-schema macro now.
    "XI_KV_SCHEMA",       # kv schema version (U2 post-Record state, doc 16)
    "XI_PLUGIN_IMPL",     # the plugin factory boilerplate
    "XI_PLUGIN_STAGED",   # opt into the v7 prepare/commit frame-perfect swap
    "XI_PLUGIN_PACK_DOOR",# publish the xi.pack@1 data-plane door (v12 sole plane)
]

def extract_exports() -> set[str]:
    """The C-ABI exports the host resolves via GetProcAddress — the authoritative
    contract surface a plugin/script AUTHOR is responsible for.

    We keep `xi_plugin_*` (the plugin C-ABI the author implements), the script
    entry `xi_inspect_entry*`, and the `xi_yyjson_abi` load gate. We DELIBERATELY
    drop the `xi_script_*` family: those are SDK plumbing GENERATED by
    xi_script_support.hpp (owner/trigger/use callbacks, get/set_state,
    code_change, …) — the author never writes them by hand; their developer-facing
    surface is the authoring macro / `xi::` function instead (e.g. code_change is
    reached via XI_STATE_SCHEMA + xi::set_state_migrate, tracked as a macro)."""
    pat = re.compile(r'GetProcAddress\([^,]+,\s*"([^"]+)"')
    out: set[str] = set()
    for base in (XI_INC, XI_SRC):
        for f in base.rglob("*.hpp"):
            out.update(pat.findall(_read(f)))
        for f in base.rglob("*.cpp"):
            out.update(pat.findall(_read(f)))
    keep = lambda s: (s.startswith("xi_plugin_")
                      or s.startswith("xi_inspect_entry")
                      or s == "xi_yyjson_abi")
    return {s for s in out if keep(s)}

def extract_macros() -> tuple[set[str], list[str]]:
    """Return (author-facing macros, any curated macro no longer #define'd)."""
    defined: set[str] = set()
    dpat = re.compile(r'#define\s+(XI_[A-Z0-9_]+)')
    for f in XI_INC.rglob("*.hpp"):
        defined.update(dpat.findall(_read(f)))
    surface = set(AUTHORING_MACROS)
    stale = [m for m in AUTHORING_MACROS if m not in defined]
    return surface, stale

# The command dispatch table lives in service_main.cpp as a single
# `g_cmd_table` map literal (`{"name", cmd_fn}` entries). This USED to be an
# `if (name == "...")` god-chain and the extractor grepped `name == "..."`; the
# TASTE refactor replaced that chain with the table, so the old pattern matched
# ZERO commands and the gate silently stopped enforcing command documentation.
# We now parse the table block itself. Fail loudly below if it can't be found or
# looks implausibly small, so this can't rot the same way twice.
WS_TABLE_MIN = 40   # sanity floor; the table has ~55 commands as of this writing.

class ExtractorError(RuntimeError):
    pass

def extract_ws_commands() -> set[str]:
    """The WS command verbs the dispatcher routes on — parsed from the
    `g_cmd_table` map literal in service_main.cpp (`{"name", handler}` entries).

    Anchored on the table's `g_cmd_table = { ... };` span so unrelated string
    literals elsewhere in the TU can't leak in. Resilient to multi-line layout /
    trailing commas (it just scans `{"literal",` entries inside the block), but
    NOT a full C++ parse — if the table is renamed or restructured, the guard
    below trips rather than silently extracting nothing."""
    text = _read(SERVICE_MAIN)
    # Isolate the table body: from `g_cmd_table = {` to the matching `};`.
    try:
        where = SERVICE_MAIN.relative_to(ROOT)
    except ValueError:
        where = SERVICE_MAIN
    m = re.search(r'g_cmd_table\s*=\s*\{', text)
    if not m:
        raise ExtractorError(
            "could not find `g_cmd_table = {` in "
            f"{where} — the WS command dispatch table "
            "moved or was renamed. The doc-coverage extractor greps that table "
            "for the command list; update extract_ws_commands() to match. "
            "(This guard exists because the extractor once silently matched ZERO "
            "commands after the if/else god-chain became this table.)")
    body = text[m.end():]
    end = body.find("};")
    if end != -1:
        body = body[:end]
    # Each entry is `{"command_name", cmd_handler_},` — grab the string key.
    cmds = set(re.findall(r'\{\s*"([a-z_]+)"\s*,', body))
    if len(cmds) < WS_TABLE_MIN:
        raise ExtractorError(
            f"extracted only {len(cmds)} WS command(s) from g_cmd_table "
            f"(expected >= {WS_TABLE_MIN}). The table format likely changed and "
            "the entry regex no longer matches — fix extract_ws_commands() in "
            "check_doc_coverage.py. Refusing to run with an implausibly small "
            "command set (a near-empty list would let undocumented commands ship, "
            "the exact regression this gate was rebuilt to catch).")
    return cmds

# --- coverage test --------------------------------------------------------

def load_allow() -> dict[str, str]:
    allow: dict[str, str] = {}
    if not ALLOW_FILE.exists():
        return allow
    for line in _read(ALLOW_FILE).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # "symbol: reason"
        sym, _, reason = line.partition(":")
        allow[sym.strip()] = reason.strip()
    return allow

def doc_text() -> str:
    chunks = []
    for root in DOC_ROOTS:
        for f in root.rglob("*.md"):
            chunks.append(_read(f))
    return "\n".join(chunks)

def export_documented(sym: str, text: str) -> bool:
    # xi_* exports are unusual tokens — a bare substring match is safe.
    return sym in text

def ws_documented(cmd: str, text: str) -> bool:
    # Require a command MARKER (cmd: prefix / quotes / backticks / heading) so a
    # bare English word like "run"/"start"/"status" in prose is not a false hit.
    forms = [f"cmd:{cmd}", f"cmd: {cmd}", f'"{cmd}"', f"`{cmd}`",
             f"### {cmd}", f"#### {cmd}"]
    return any(fm in text for fm in forms)

def main() -> int:
    text = doc_text()
    allow = load_allow()

    exports = extract_exports()
    try:
        commands = extract_ws_commands()
    except ExtractorError as e:
        print("[doc-coverage] FAIL: WS-command extractor broke\n")
        print(e)
        return 1
    macros, stale_macros = extract_macros()

    missing: list[tuple[str, str]] = []      # (kind, name)
    for sym in sorted(exports):
        if sym in allow:
            continue
        if not export_documented(sym, text):
            missing.append(("export", sym))
    for mac in sorted(macros):
        if mac in allow:
            continue
        if not export_documented(mac, text):   # macros are unusual tokens too
            missing.append(("macro", mac))
    for cmd in sorted(commands):
        if cmd in allow:
            continue
        if not ws_documented(cmd, text):
            missing.append(("cmd", cmd))

    # A stale allow-entry (symbol that no longer exists) is itself a smell.
    known = exports | commands | macros
    stale = sorted(s for s in allow if s not in known)

    doc_dirs = ", ".join(str(r.relative_to(ROOT)) for r in DOC_ROOTS)
    print(f"[doc-coverage] {len(exports)} exports + {len(macros)} macros + "
          f"{len(commands)} WS commands vs {doc_dirs}")
    print(f"[doc-coverage] {len(allow)} allow-listed exception(s)")

    if stale_macros:
        print("\nSTALE curated macro(s) (AUTHORING_MACROS lists a macro no longer "
              "#define'd — fix the list in check_doc_coverage.py):")
        for m in stale_macros:
            print(f"  - {m}")

    if stale:
        print("\nSTALE allow-list entries (symbol no longer in the source surface — "
              "remove them):")
        for s in stale:
            print(f"  - {s}")

    if missing:
        print(f"\nUNDOCUMENTED public surface ({len(missing)}): each must be "
              f"documented in {doc_dirs},")
        print("or, if genuinely internal, added to docs/.doc-coverage-allow "
              "with a reason.\n")
        for kind, name in missing:
            hint = ("ws-protocol.md" if kind == "cmd" else
                    "c-abi.md / write-a-plugin.md / write-a-script.md")
            print(f"  [{kind:6}] {name}   -> document in {hint}")
        print()

    if missing or stale or stale_macros:
        return 1
    print("[doc-coverage] OK -- every public export + WS command is documented.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
