#!/usr/bin/env python3
"""gen_backend_map.py — regenerate backend/src/MAP.md, the coding-agent map.

WHY THIS EXISTS
---------------
A coding agent dropped into backend/ has to answer three questions fast:
  1. what does each translation unit / header actually own?
  2. which .cpp defines the handler for WS command `foo`?
  3. what does plugin `bar` declare (lib? autoload? which exchange verbs)?
Answering them by hand means grepping a table in service_main.cpp, chasing a
handler symbol across five service_cmd_*.cpp files, and reading every
plugin.json. This tool does that mechanically and writes MAP.md, so the map can
never silently drift from the source: a `--check` mode (wired as the
`backend_map_check` ctest) fails if the committed MAP.md is stale.

DISCOVERY, NOT ASSUMPTION
-------------------------
Nothing here hardcodes a file list. The command table is found by scanning every
backend/src/*.cpp for the `g_cmd_table = { ... }` literal; handler symbols are
resolved to their defining file by indexing every `void cmd_*_(... ws::Server`
definition across all TUs; responsibilities come from each file's top comment;
plugins come from globbing toolbox/**/plugin.json. A parallel branch is splitting
service_cmd_lifecycle.cpp — that rename changes the OUTPUT rows, never this code.

USAGE
-----
  python tools/gen_backend_map.py            # regenerate backend/src/MAP.md
  python tools/gen_backend_map.py --check     # exit 1 (with a diff) if stale

Deterministic output: stable sort, LF newlines, UTF-8 no BOM — so the gate diff
is byte-stable across machines.
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
XI_SRC = ROOT / "backend" / "src"
XI_INC = ROOT / "backend" / "include" / "xi"
TOOLBOX = ROOT / "toolbox"
OUT = XI_SRC / "MAP.md"

MARKER = ("<!-- AUTO-GENERATED by tools/gen_backend_map.py — do not edit; "
          "regenerate with: python tools/gen_backend_map.py -->")

# A near-empty command table almost always means the table format changed and
# the entry regex stopped matching, not that the backend lost its commands. Fail
# loudly rather than emit a hollow map (mirrors check_doc_coverage.py's floor).
WS_TABLE_MIN = 30


class ExtractorError(RuntimeError):
    pass


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def _rel(p: Path) -> str:
    try:
        return p.relative_to(ROOT).as_posix()
    except ValueError:
        return p.as_posix()


# --- ① file-top responsibility one-liners ----------------------------------

def top_responsibility(path: Path) -> str:
    """First sentence of a file's top comment block, comment markers stripped.

    Handles the two shapes in this tree: a `//` banner (optionally after
    `#pragma once`) and the occasional `/* ... */`. The banner's first content
    line is `<filename> — <what it is>`; we keep the text after the em/en dash
    when present (that IS the responsibility), else the whole first sentence.
    """
    text = _read(path)
    lines = text.splitlines()
    collected: list[str] = []
    started = False
    for raw in lines:
        s = raw.strip()
        if not started:
            if s == "" or s == "#pragma once":
                continue
            if s.startswith("//") or s.startswith("/*"):
                started = True
            else:
                # Code before any banner comment -> no top comment.
                break
        if not started:
            continue
        if s.startswith("//"):
            body = s[2:].strip()
            if set(body) <= {"=", "-", "/"} and body:  # rule line -> banner end
                if collected:
                    break
                continue
            collected.append(body)
        elif s.startswith("/*"):
            body = s.lstrip("/*").strip()
            if body:
                collected.append(body)
        elif s.startswith("*"):
            body = s.lstrip("*").strip()
            if body.endswith("*/"):
                body = body[:-2].strip()
            if body:
                collected.append(body)
            if s.endswith("*/"):
                break
        elif collected:
            break
    if not collected:
        return ""
    blob = " ".join(collected).strip()
    # Drop a leading "<filename> — " / "<filename>: " label if present.
    name = path.name
    m = re.match(rf"^{re.escape(name)}\s*[—–:-]\s*(.*)$", blob)
    if m:
        blob = m.group(1).strip()
    # First sentence: up to the first ". " that ends a sentence (not "e.g.").
    sentence = _first_sentence(blob)
    return _cap(sentence)


def _first_sentence(text: str) -> str:
    # A sentence ends at a period (optionally `.)`) followed by whitespace or EOF.
    # We deliberately do NOT treat `;` as a boundary — these banners use `;`
    # inside parentheticals ("(behavior-preserving; see ...)"). Skip periods that
    # belong to a known abbreviation carrying an internal dot.
    ABBREV = ("e.g", "i.e", "vs", "cf", "etc")
    idx = 0
    while True:
        m = re.search(r"\.(\)?)(\s+|$)", text[idx:])
        if not m:
            return text.strip()
        end = idx + m.start()
        tail = text[max(0, end - 4):end]
        if any(tail.endswith(a) for a in ABBREV):
            idx = end + 1
            continue
        return text[:end + 1 + len(m.group(1))].strip()


def _cap(text: str, limit: int = 200) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= limit:
        return text
    cut = text[:limit].rsplit(" ", 1)[0]
    return cut + "…"


# --- ② command -> handler -> defining file ---------------------------------

def find_cmd_table_file() -> Path:
    """The single backend/src/*.cpp carrying the `g_cmd_table` map literal."""
    hits = [f for f in sorted(XI_SRC.glob("*.cpp"))
            if re.search(r"g_cmd_table\s*=\s*\{", _read(f))]
    if not hits:
        raise ExtractorError(
            "no backend/src/*.cpp contains a `g_cmd_table = {` literal — the WS "
            "dispatch table moved or was renamed. Update find_cmd_table_file().")
    if len(hits) > 1:
        raise ExtractorError(
            "more than one TU defines `g_cmd_table`: "
            + ", ".join(_rel(h) for h in hits))
    return hits[0]


def extract_commands() -> list[tuple[str, str]]:
    """[(command, handler_symbol)] parsed from the g_cmd_table literal."""
    src = find_cmd_table_file()
    text = _read(src)
    m = re.search(r"g_cmd_table\s*=\s*\{", text)
    body = text[m.end():]
    end = body.find("};")
    if end != -1:
        body = body[:end]
    pairs = re.findall(r'\{\s*"([a-z_]+)"\s*,\s*([A-Za-z_]\w*)\s*\}', body)
    if len(pairs) < WS_TABLE_MIN:
        raise ExtractorError(
            f"extracted only {len(pairs)} command(s) from g_cmd_table in "
            f"{_rel(src)} (expected >= {WS_TABLE_MIN}); the entry format likely "
            "changed and the regex no longer matches — fix extract_commands().")
    return pairs


def index_handlers() -> dict[str, Path]:
    """Map every `void cmd_*_(...ws::Server` handler symbol to its defining TU."""
    # Signature shape verified in-tree:
    #   void cmd_ping_(xi::ws::Server& srv, int64_t id, const xp::ParsedCmd* parsed)
    pat = re.compile(
        r"^\s*(?:static\s+)?void\s+(cmd_\w+?_)\s*\(\s*xi::ws::Server\b",
        re.MULTILINE)
    out: dict[str, Path] = {}
    for f in sorted(XI_SRC.glob("*.cpp")):
        for sym in pat.findall(_read(f)):
            out.setdefault(sym, f)
    return out


# --- ③ plugins --------------------------------------------------------------

FLAG_KEYS = ("lib", "autoload", "has_ui", "sink", "reentrant")


def extract_plugins() -> list[dict]:
    plugins = []
    for pj in sorted(TOOLBOX.rglob("plugin.json")):
        try:
            data = json.loads(_read(pj))
        except json.JSONDecodeError as e:
            raise ExtractorError(f"{_rel(pj)}: invalid JSON ({e})")
        manifest = data.get("manifest", {}) or {}
        flags = [k for k in FLAG_KEYS if data.get(k)]
        exchange = sorted(
            str(e.get("command", "")) for e in manifest.get("exchange", []) or []
            if e.get("command"))
        caps = sorted(
            str(c.get("name", "")) for c in manifest.get("capabilities", []) or []
            if c.get("name"))
        plugins.append({
            "name": str(data.get("name") or pj.parent.name),
            "path": _rel(pj),
            "dll": str(data.get("dll", "")),
            "flags": flags,
            "exchange": exchange,
            "capabilities": caps,
        })
    plugins.sort(key=lambda p: (p["name"], p["path"]))
    return plugins


def extract_pluginlets() -> list[dict]:
    lets = []
    for pj in sorted(TOOLBOX.rglob("pluginlet.json")):
        try:
            data = json.loads(_read(pj))
        except json.JSONDecodeError as e:
            raise ExtractorError(f"{_rel(pj)}: invalid JSON ({e})")
        halves = data.get("halves", {}) or {}
        native = (halves.get("native", {}) or {}).get("symbol", "")
        ui = (halves.get("ui", {}) or {}).get("entry", "")
        lets.append({
            "name": str(data.get("name") or pj.parent.name),
            "path": _rel(pj),
            "native": str(native),
            "ui": str(ui),
        })
    lets.sort(key=lambda p: p["name"])
    return lets


# --- render -----------------------------------------------------------------

def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ") if text else ""


def render() -> str:
    src_files = sorted(XI_SRC.glob("*.cpp")) + sorted(XI_SRC.glob("*.hpp"))
    hdr_files = sorted(XI_INC.glob("*.hpp"))
    commands = extract_commands()
    handlers = index_handlers()
    plugins = extract_plugins()
    pluginlets = extract_pluginlets()

    L: list[str] = []
    L.append(MARKER)
    L.append("")
    L.append("# Backend map")
    L.append("")
    L.append("Machine-generated navigation index for coding agents. For the "
             "hand-written \"find X → do Y\" recipes see "
             "[docs/agent/NAVIGATION.md](../../docs/agent/NAVIGATION.md).")
    L.append("")

    # ① responsibilities
    L.append("## ① Translation units & headers")
    L.append("")
    L.append("First sentence of each file's top comment (its responsibility).")
    L.append("")
    L.append("### backend/src")
    L.append("")
    L.append("| File | Responsibility |")
    L.append("| --- | --- |")
    for f in src_files:
        L.append(f"| `{f.name}` | {_cell(top_responsibility(f))} |")
    L.append("")
    L.append("### backend/include/xi")
    L.append("")
    L.append("| Header | Responsibility |")
    L.append("| --- | --- |")
    for f in hdr_files:
        L.append(f"| `{f.name}` | {_cell(top_responsibility(f))} |")
    L.append("")

    # ② commands
    L.append("## ② WS commands → handler → defining file")
    L.append("")
    L.append(f"Parsed from `g_cmd_table` in "
             f"`{_rel(find_cmd_table_file())}`.")
    L.append("")
    L.append("| Command | Handler | Defined in |")
    L.append("| --- | --- | --- |")
    for cmd, sym in sorted(commands):
        f = handlers.get(sym)
        where = f"`backend/src/{f.name}`" if f else "_(handler not found)_"
        L.append(f"| `{cmd}` | `{sym}` | {where} |")
    L.append("")

    # ③ plugins
    L.append("## ③ Plugins (toolbox/*/plugin.json)")
    L.append("")
    L.append("Flags: `lib` = capability provider (no data plane); `autoload` = "
             "boot-time eligible; `has_ui` = ships a webUI; `sink` = ordered "
             "output sink; `reentrant` = no per-instance serialization.")
    L.append("")
    L.append("| Plugin | Flags | Exchange verbs | Capabilities |")
    L.append("| --- | --- | --- | --- |")
    for p in plugins:
        flags = ", ".join(f"`{x}`" for x in p["flags"]) or "—"
        ex = ", ".join(f"`{x}`" for x in p["exchange"]) or "—"
        caps = ", ".join(f"`{x}`" for x in p["capabilities"]) or "—"
        L.append(f"| `{p['name']}` ({p['path']}) | {flags} | {ex} | {caps} |")
    L.append("")

    # pluginlets (structurally distinct: header-delivered UI halves, doc 37)
    if pluginlets:
        L.append("## ④ Pluginlets (toolbox/pluginlets/*/pluginlet.json)")
        L.append("")
        L.append("Parasitic UI/logic halves compiled into a host, not standalone "
                 "plugins (docs/new_gen/37-pluginlet-model.md).")
        L.append("")
        L.append("| Pluginlet | Native symbol | UI entry |")
        L.append("| --- | --- | --- |")
        for p in pluginlets:
            L.append(f"| `{p['name']}` ({p['path']}) | `{p['native']}` | "
                     f"`{p['ui']}` |")
        L.append("")

    return "\n".join(L).rstrip("\n") + "\n"


# --- main -------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero (with a diff) if MAP.md is stale")
    args = ap.parse_args()

    try:
        generated = render()
    except ExtractorError as e:
        print(f"gen_backend_map: EXTRACTOR ERROR: {e}", file=sys.stderr)
        return 2

    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        # Compare on normalized LF so a CRLF checkout doesn't false-fail.
        if current.replace("\r\n", "\n") == generated:
            print(f"gen_backend_map: {_rel(OUT)} is up to date.")
            return 0
        diff = difflib.unified_diff(
            current.replace("\r\n", "\n").splitlines(),
            generated.splitlines(),
            fromfile=f"{_rel(OUT)} (committed)",
            tofile=f"{_rel(OUT)} (regenerated)",
            lineterm="")
        sys.stderr.write("\n".join(list(diff)[:80]))
        sys.stderr.write(
            f"\n\ngen_backend_map: {_rel(OUT)} is STALE — regenerate with "
            "`python tools/gen_backend_map.py` and commit.\n")
        return 1

    # UTF-8, no BOM, LF newlines.
    OUT.write_bytes(generated.encode("utf-8"))
    print(f"gen_backend_map: wrote {_rel(OUT)} "
          f"({generated.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
