/*
 * xi_abi.h — the universal plugin interface for xInsp2.
 *
 * ALL plugins use this interface — built-in, third-party, native scripts.
 * Pure C types at the boundary. Stable across compiler versions.
 *
 * Key concept: images are refcounted HANDLES managed by the host.
 * Plugins never malloc/free image buffers — they ask the host to create
 * images, get a handle back, read/write via the host API, and release
 * when done. Caching = addref. Passing between plugins = zero copy
 * (just pass the handle).
 *
 * Flow:
 *
 *   1. Backend loads plugin DLL
 *   2. Calls xi_plugin_create(host_api, name) → opaque instance
 *   3. Calls xi_plugin_process(inst, input_record, output_record)
 *      - input images are handles the backend owns
 *      - plugin reads via host->image_data(handle)
 *      - plugin creates output images via host->image_create()
 *      - plugin puts output handles in the output record
 *      - to cache an input image: host->image_addref(handle)
 *   4. Backend reads output record, takes ownership of output handles
 *   5. When done: host->image_release() on all handles
 */

#ifndef XI_ABI_H
#define XI_ABI_H

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* ABI version — bumped on any semantic change to the surfaces       */
/* below. Plugins compiled against version N require a host with     */
/* version >= N (forward compatible — newer host runs older          */
/* plugin), but a host running a plugin compiled against a newer     */
/* version than itself may see null fn pointers in xi_host_api.      */
/*                                                                    */
/* The plugin loader gates on this: a plugin's xi_plugin_abi_version */
/* export (generated by XI_PLUGIN_IMPL) is checked against the       */
/* host's XI_ABI_VERSION and the plugin is refused if it asks for a  */
/* newer ABI than the host provides.                                  */
/*                                                                    */
/* Current version history:                                           */
/*   1 — initial frozen surface (image pool, trigger bus, SHM, host  */
/*       api with read_image_file).                                  */
/* ------------------------------------------------------------------ */
#define XI_ABI_VERSION 1

/* ------------------------------------------------------------------ */
/* Image handle — opaque reference to a refcounted image in the host  */
/* ------------------------------------------------------------------ */

typedef uint64_t xi_image_handle;
#define XI_IMAGE_NULL 0

/* ------------------------------------------------------------------ */
/* Trigger ID — 128-bit identifier for a single inspection event.     */
/* Sources tag every emitted frame with one. Frames sharing a tid are */
/* correlated (e.g., synchronized multi-camera capture). The host's   */
/* TriggerBus groups them and dispatches the script once per tid.     */
/* ------------------------------------------------------------------ */

typedef struct { uint64_t hi; uint64_t lo; } xi_trigger_id;

#ifdef __cplusplus
#define XI_TRIGGER_NULL (xi_trigger_id{0, 0})
#else
#define XI_TRIGGER_NULL ((xi_trigger_id){0, 0})
#endif

static inline int xi_trigger_id_eq(xi_trigger_id a, xi_trigger_id b) {
    return a.hi == b.hi && a.lo == b.lo;
}
static inline int xi_trigger_id_is_null(xi_trigger_id a) {
    return a.hi == 0 && a.lo == 0;
}

/* ------------------------------------------------------------------ */
/* Record image entry — defined before xi_host_api so emit_trigger    */
/* can reference it.                                                  */
/* ------------------------------------------------------------------ */

typedef struct {
    const char*      key;       /* borrowed — valid for duration of the call */
    xi_image_handle  handle;
} xi_record_image;

/* ------------------------------------------------------------------ */
/* Host API — function table provided by the backend to every plugin  */
/* ------------------------------------------------------------------ */

typedef struct xi_host_api {
    /* Image pool */
    xi_image_handle (*image_create)(int32_t w, int32_t h, int32_t channels);
    void            (*image_addref)(xi_image_handle h);
    void            (*image_release)(xi_image_handle h);
    uint8_t*        (*image_data)(xi_image_handle h);
    int32_t         (*image_width)(xi_image_handle h);
    int32_t         (*image_height)(xi_image_handle h);
    int32_t         (*image_channels)(xi_image_handle h);
    int32_t         (*image_stride)(xi_image_handle h);

    /* Logging */
    void (*log)(int32_t level, const char* msg);
    /* level: 0=debug, 1=info, 2=warn, 3=error */

    /* Lookup the on-disk folder for a named instance. The folder is
     * created by the host before xi_plugin_create() is called and is the
     * right place to persist plugin-specific data (calibration files,
     * lookup tables, captured frames, ML weights — anything beyond the
     * small JSON config returned by get_def).
     *
     * Writes the path (without trailing slash) into buf, returns bytes
     * written, or -needed if buflen is too small. Returns 0 if the
     * instance is unknown to the host. */
    int32_t (*instance_folder)(const char* instance_name, char* buf, int32_t buflen);

    /* Image-source plugins call this to publish a frame (or set of
     * frames) tagged with a trigger ID. The host's TriggerBus groups
     * frames sharing a tid and dispatches the script once per complete
     * trigger.
     *
     *   source_name:   the publishing instance's name (xi::Plugin::name())
     *   tid:           caller-supplied 128-bit identifier; XI_TRIGGER_NULL
     *                  asks the host to allocate a fresh one.
     *   timestamp_us:  capture timestamp in microseconds (host clock).
     *                  Pass 0 to use the host's current time.
     *   images:        the frame(s) being published. The bus addrefs each
     *                  handle internally — the caller may release them
     *                  immediately after this call returns.
     *   image_count:   number of entries in `images`.
     */
    void (*emit_trigger)(const char* source_name,
                         xi_trigger_id tid,
                         int64_t timestamp_us,
                         const xi_record_image* images,
                         int32_t image_count);

    /* --------------------------------------------------------------- */
    /* SHM zero-copy buffer pool (opt-in, added in v2 of the host API) */
    /* --------------------------------------------------------------- */
    /* Plugins / scripts call these when they want to allocate an image
     * or buffer that the OTHER side (a worker process, the host, a
     * different plugin) can deref WITHOUT a memcpy. Returned handle
     * lives in the same uint64 namespace as image_handle, so all the
     * existing image_data / image_width / ... functions also work on
     * SHM-backed handles transparently.
     *
     * If shm_create_image is null, the host has no SHM region (older
     * host or feature disabled). Callers should fall back to
     * image_create in that case.
     *
     *   size_bytes for shm_alloc_buffer: an opaque byte buffer (e.g.
     *     ML weights, big metadata). image_data() returns the start.
     *
     * Refcount semantics match image_addref / image_release.
     */
    xi_image_handle (*shm_create_image)(int32_t w, int32_t h, int32_t channels);
    xi_image_handle (*shm_alloc_buffer)(int32_t size_bytes);
    void            (*shm_addref)(xi_image_handle h);
    void            (*shm_release)(xi_image_handle h);
    /* Returns 1 if the handle came from the SHM region, 0 if heap. */
    int32_t         (*shm_is_shm_handle)(xi_image_handle h);

    /* --------------------------------------------------------------- */
    /* File I/O (host-provided so plugins / scripts don't have to vendor
     * stb_image themselves). Reads PNG / JPEG / BMP / TGA / GIF /
     * PSD / HDR / PIC into a fresh image_create-allocated handle.
     * Returns 0 on failure (file missing, decode error, OOM).
     *
     * The returned handle has refcount 1; the caller is responsible
     * for image_release when done. */
    xi_image_handle (*read_image_file)(const char* path);
} xi_host_api;

/* ------------------------------------------------------------------ */
/* Record — the universal data container crossing the boundary        */
/* ------------------------------------------------------------------ */

/* A record: named images + JSON metadata. */
typedef struct {
    const xi_record_image* images;
    int32_t                image_count;
    const char*            json;    /* null-terminated JSON object string */
} xi_record;

/* Output record — plugin fills this during process(). */
typedef struct {
    xi_record_image* images;
    int32_t          image_count;
    int32_t          image_capacity;
    char*            json;          /* plugin sets this (malloc'd, caller frees) */
} xi_record_out;

/* Helpers for building output records */

static inline void xi_record_out_init(xi_record_out* out) {
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->json = NULL;
}

static inline void xi_record_out_add_image(xi_record_out* out,
                                            const char* key,
                                            xi_image_handle handle) {
    if (out->image_count >= out->image_capacity) {
        int32_t new_cap = out->image_capacity ? out->image_capacity * 2 : 8;
        xi_record_image* arr = (xi_record_image*)realloc(
            out->images, (size_t)new_cap * sizeof(xi_record_image));
        if (!arr) return;
        out->images = arr;
        out->image_capacity = new_cap;
    }
    xi_record_image* entry = &out->images[out->image_count++];
    entry->key = _strdup(key);
    entry->handle = handle;
}

static inline void xi_record_out_set_json(xi_record_out* out, const char* json) {
    free(out->json);
    out->json = _strdup(json);
}

/* Free strings the plugin allocated via the inline malloc/strdup
 * helpers above. SAFE TO CALL on outputs populated by `record_to_c`
 * (xi_abi.hpp) — `image_capacity == 0` signals "plugin-owned tls
 * storage; nothing to free", which is the path the C++ macro generates.
 *
 * Background: when these helpers are inlined into a plugin DLL that
 * uses a different CRT than the backend EXE, the plugin's `_strdup` /
 * `realloc` is paired with the backend's `free()` — undefined
 * behaviour. The C++ helpers in `xi_abi.hpp::record_to_c` route output
 * strings through thread-local storage owned by the plugin DLL, so no
 * cross-CRT free happens. Direct-C plugins that call
 * `xi_record_out_add_image` etc still use the malloc path and are
 * safe ONLY if the plugin and backend share a CRT (the CMake default
 * `/MD` does this). */
static inline void xi_record_out_free(xi_record_out* out) {
    if (out->image_capacity > 0) {
        /* Legacy / direct-C path: plugin used the realloc + strdup
         * helpers. Free with the same allocator the calling EXE was
         * compiled against (best effort; same-CRT contract). */
        for (int32_t i = 0; i < out->image_count; ++i) {
            free((void*)out->images[i].key);
        }
        free(out->images);
        free(out->json);
    }
    /* image_capacity == 0: plugin-owned thread-local storage, no free. */
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->json = NULL;
}

/* ------------------------------------------------------------------ */
/* Plugin entry points — exported by every plugin DLL                 */
/* ------------------------------------------------------------------ */

/*
 * xi_plugin_create(host, name) → opaque instance pointer
 *   Called once per instance. Plugin stores the host_api pointer for
 *   later use (image_create, image_data, etc.)
 *
 * xi_plugin_destroy(inst)
 *   Release all cached handles and free the instance.
 *
 * xi_plugin_process(inst, input, output)
 *   Run the plugin's core logic. Read input images via host->image_data().
 *   Create output images via host->image_create(). Put handles in output.
 *
 * xi_plugin_exchange(inst, cmd_json, rsp_buf, rsp_buflen) → bytes written
 *   UI/config commands. Returns JSON response.
 *
 * xi_plugin_get_def(inst, buf, buflen) → bytes written
 *   Serialize current config to JSON.
 *
 * xi_plugin_set_def(inst, json) → 0 on success
 *   Restore config from JSON.
 */

/* Type signatures for GetProcAddress */
typedef void* (*xi_plugin_create_fn)(const xi_host_api* host, const char* name);
typedef void  (*xi_plugin_destroy_fn)(void* inst);
typedef void  (*xi_plugin_process_fn)(void* inst, const xi_record* input, xi_record_out* output);
typedef int   (*xi_plugin_exchange_fn)(void* inst, const char* cmd, char* rsp, int rsplen);
typedef int   (*xi_plugin_get_def_fn)(void* inst, char* buf, int buflen);
typedef int   (*xi_plugin_set_def_fn)(void* inst, const char* json);

#ifdef __cplusplus
}
#endif

#endif /* XI_ABI_H */
