/*
 * xi_abi.h — the universal plugin interface for xInsp2.
 *
 * ALL plugins use this interface — built-in, third-party, native scripts.
 * Pure C types at the boundary. Stable across compiler versions.
 *
 * Key concept: images are refcounted HANDLES managed by the host.
 * Plugins never malloc/free image buffers — they ask the host to create
 * images, get a handle back, read/write via the host API, and release
 * when done. Caching = addref. Passing between plugins = zero copy
 * (just pass the handle).
 *
 * Flow:
 *
 *   1. Backend loads plugin DLL
 *   2. Calls xi_plugin_create(host_api, name) → opaque instance
 *   3. Calls xi_plugin_process(inst, input_record, output_record)
 *      - input images are handles the backend owns
 *      - plugin reads via host->image_data(handle)
 *      - plugin creates output images via host->image_create()
 *      - plugin puts output handles in the output record
 *      - to cache an input image: host->image_addref(handle)
 *   4. Backend reads output record, takes ownership of output handles
 *   5. When done: host->image_release() on all handles
 */

#ifndef XI_ABI_H
#define XI_ABI_H

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* ABI version — bumped on any semantic change to the surfaces       */
/* below. Plugins compiled against version N require a host with     */
/* version >= N (forward compatible — newer host runs older          */
/* plugin), but a host running a plugin compiled against a newer     */
/* version than itself may see null fn pointers in xi_host_api.      */
/*                                                                    */
/* The plugin loader gates on this: a plugin's xi_plugin_abi_version */
/* export (generated by XI_PLUGIN_IMPL) is checked against the       */
/* host's XI_ABI_VERSION and the plugin is refused if it asks for a  */
/* newer ABI than the host provides.                                  */
/*                                                                    */
/* Current version history:                                           */
/*   1 — initial frozen surface (image pool, trigger bus, SHM [fields  */
/*       retained for layout stability; SHM removed 2026-05, always  */
/*       null on current hosts], host api with read_image_file).     */
/*   2 — + emit_resource (emit/fetch resource store). Additive at the */
/*       struct tail, so v1 plugins keep working unchanged.          */
/*   3 — + in-process doc pass-by-pointer (γ): xi_record.doc /        */
/*       xi_record_out.out_doc carry a borrowed/host-owned           */
/*       yyjson_mut_doc* so an in-process call skips the JSON         */
/*       serialize round-trip; doc_chunk_* host allocator backs       */
/*       host-owned docs; the xi_yyjson_abi() plugin export gates it  */
/*       on a matching yyjson layout. All additive at the tail; when  */
/*       the doc pointer is null (older plugin / mismatch / cross-    */
/*       process) the data/len JSON path is used exactly as in v2.    */
/*   4 — + doc_retain/doc_release/doc_refcount (γ-4): a host-side     */
/*       refcount for a yyjson_mut_doc handed across the ABI,         */
/*       mirroring image_addref/release. Lets a doc pointer be held   */
/*       by more than one side (host adopting a doc a plugin still    */
/*       caches; a plugin caching its borrowed input) with no deep    */
/*       copy; doc_refcount lets the adopter learn if it is the sole  */
/*       side. Additive at the tail; null on a pre-v4 host ⇒ callers  */
/*       fall back to the v3 deep-copy / serialize behaviour.         */
/*   5 — + emit_trigger_record: emit_trigger that also carries a       */
/*       JSON metadata doc, by handing the host a whole xi_record      */
/*       (images + data/len + doc) instead of a bare image array.      */
/*       The metadata travels with the event on the trigger bus —      */
/*       correlated through the same policy as the frames — and is      */
/*       read script-side via current_trigger().meta(). It is the      */
/*       routing/context channel the bare emit_trigger lacked          */
/*       (command id, recipe, lane hint).                              */
/*                                                                     */
/*       Zero-serialize: rec->doc (a HOST-OWNED yyjson_mut_doc*, built */
/*       via doc_chunk_*) is carried across the async dispatch by      */
/*       POINTER, refcounted through doc_retain/doc_release — exactly  */
/*       as image handles ride the ImagePool refcount. A plugin-owned  */
/*       bare doc must NOT be passed (its free can't be reconciled);   */
/*       the SDK emit() helper builds a host-owned record. Only the    */
/*       recorder serializes, and only when persisting to disk.        */
/*                                                                     */
/*       Additive at the tail; emit_trigger is exactly                 */
/*       emit_trigger_record with empty metadata, so a pre-v5 host     */
/*       (the pointer is null) just loses the metadata, never the      */
/*       frames.                                                       */
/*   6 — Dispatch model collapsed to ONE plugin verb: emit_trigger_    */
/*       record renamed `emit_record(emitter, id, rec, ts)` (stage +   */
/*       dispatch a record). The trigger bus + correlation policies     */
/*       (Any/AllRequired/LeaderFollowers) and the host record/replay  */
/*       are gone — multi-camera sync is now a gathering plugin (one    */
/*       record, N images) and replay is a buffer-replay plugin.       */
/*       `emit_trigger`, `emit_resource`, `fetch_resource`,            */
/*       `fetch_image`, `emit_dispatch` are RETIRED and REMOVED in the */
/*       dispatch cleanup (no v4 binary compat kept — every plugin     */
/*       rebuilds against v6). A source must now use emit_record. The   */
/*       script reads the dispatched record via current_trigger().     */
/*       image()/.meta(); cmd:run injects the same way for headless    */
/*       tests. See internals/dispatch.md.                             */
/*   7 — + frame-perfect config swap: two OPTIONAL plugin exports,      */
/*       xi_plugin_prepare(inst, def_json, folder) and                 */
/*       xi_plugin_commit(inst). prepare() loads heavy assets into a    */
/*       plugin-internal BACKGROUND staging slot (the live config keeps  */
/*       running); commit() atomically swaps staging -> live. The host  */
/*       calls prepare OUTSIDE its per-instance serialization gate (it  */
/*       runs concurrent with process(), so the load doesn't stall the  */
/*       pipeline) — a plugin only gets this by opting in with the      */
/*       XI_PLUGIN_STAGED macro, whose contract is "prepare touches the */
/*       staging slot ONLY, never live state". commit runs gated. Both  */
/*       are resolved via GetProcAddress: a plugin without them falls   */
/*       back to gated set_def (prepare) / no-op (commit), so simple    */
/*       plugins need neither. These are PLUGIN exports (host->plugin), */
/*       not xi_host_api fields, so they don't shift any struct — an    */
/*       older host simply never calls them. The host pairs prepare     */
/*       with commit_group (a drain-barrier) for frame-perfect group    */
/*       switches. See roadmap/config-bundles-and-orchestration.md.     */
/* ------------------------------------------------------------------ */
#define XI_ABI_VERSION 9   /* v8: + emit_binary; v9: + compress_image (host JPEG cache) */

/* Oldest plugin ABI the host loads; bump on every breaking xi_host_api layout change. */
#define XI_ABI_MIN_COMPAT 6

/* Expected sizeof(xi_host_api) for the layout guard below (see the ABI LAYOUT
 * GUARD note after the struct). Bump together with XI_ABI_VERSION on any layout
 * change. 64-bit host (all function pointers). */
#define XI_ABI_EXPECTED_SIZE 208  /* 64-bit: 26 function pointers * 8 bytes */

/* ------------------------------------------------------------------ */
/* Image handle — opaque reference to a refcounted image in the host  */
/* ------------------------------------------------------------------ */

typedef uint64_t xi_image_handle;
#define XI_IMAGE_NULL 0

/* ------------------------------------------------------------------ */
/* Trigger ID — 128-bit identifier for a single inspection event.     */
/* Sources tag every emitted frame with one. Frames sharing a tid are */
/* correlated (e.g., synchronized multi-camera capture). The host's   */
/* TriggerBus groups them and dispatches the script once per tid.     */
/* ------------------------------------------------------------------ */

typedef struct { uint64_t hi; uint64_t lo; } xi_trigger_id;

#ifdef __cplusplus
#define XI_TRIGGER_NULL (xi_trigger_id{0, 0})
#else
#define XI_TRIGGER_NULL ((xi_trigger_id){0, 0})
#endif

static inline int xi_trigger_id_eq(xi_trigger_id a, xi_trigger_id b) {
    return a.hi == b.hi && a.lo == b.lo;
}
static inline int xi_trigger_id_is_null(xi_trigger_id a) {
    return a.hi == 0 && a.lo == 0;
}

/* ------------------------------------------------------------------ */
/* Record image entry — defined before xi_host_api so emit_trigger    */
/* can reference it.                                                  */
/* ------------------------------------------------------------------ */

typedef struct {
    const char*      key;       /* borrowed — valid for duration of the call */
    xi_image_handle  handle;
} xi_record_image;

/* Forward declaration so emit_trigger_record (ABI v5) can take a whole
 * record. The full definition (tagged `struct xi_record`) is below, after
 * xi_host_api, since the record carries no host-api types itself. */
struct xi_record;

/* ------------------------------------------------------------------ */
/* Host API — function table provided by the backend to every plugin  */
/* ------------------------------------------------------------------ */

typedef struct xi_host_api {
    /* Image pool */
    xi_image_handle (*image_create)(int32_t w, int32_t h, int32_t channels);
    void            (*image_addref)(xi_image_handle h);
    void            (*image_release)(xi_image_handle h);
    uint8_t*        (*image_data)(xi_image_handle h);
    int32_t         (*image_width)(xi_image_handle h);
    int32_t         (*image_height)(xi_image_handle h);
    int32_t         (*image_channels)(xi_image_handle h);
    int32_t         (*image_stride)(xi_image_handle h);

    /* Logging */
    void (*log)(int32_t level, const char* msg);
    /* level: 0=debug, 1=info, 2=warn, 3=error */

    /* Lookup the on-disk folder for a named instance. The folder is
     * created by the host before xi_plugin_create() is called and is the
     * right place to persist plugin-specific data (calibration files,
     * lookup tables, captured frames, ML weights — anything beyond the
     * small JSON config returned by get_def).
     *
     * Writes the path (without trailing slash) into buf, returns bytes
     * written, or -needed if buflen is too small. Returns 0 if the
     * instance is unknown to the host. */
    int32_t (*instance_folder)(const char* instance_name, char* buf, int32_t buflen);

    /* --------------------------------------------------------------- */
    /* SHM zero-copy buffer pool — RETAINED FOR ABI STABILITY ONLY.   */
    /* SHM and the out-of-process comms gateway were removed 2026-05.  */
    /* ALL five function pointers below are NULL on current hosts and  */
    /* will remain NULL until/unless SHM is re-introduced. Plugins     */
    /* MUST null-check before calling (as the original contract         */
    /* already required). Fields are kept in place — removing them     */
    /* would shift every subsequent function pointer and break binary   */
    /* compatibility with plugins compiled against ABI v1/v2.          */
    /*                                                                  */
    /* Historical note: these were intended to allow a worker process   */
    /* or different plugin to deref image buffers without a memcpy.     */
    /* The opt-in design (null == unavailable) means existing code      */
    /* that already null-checks continues to work with no change.       */
    /*                                                                  */
    /*   size_bytes for shm_alloc_buffer: opaque byte buffer (e.g.     */
    /*     ML weights, big metadata). image_data() returns the start.  */
    /*                                                                  */
    /* Refcount semantics (when non-null) match image_addref/release.   */
    /* --------------------------------------------------------------- */
    xi_image_handle (*shm_create_image)(int32_t w, int32_t h, int32_t channels);
    xi_image_handle (*shm_alloc_buffer)(int32_t size_bytes);
    void            (*shm_addref)(xi_image_handle h);
    void            (*shm_release)(xi_image_handle h);
    /* Returns 1 if the handle came from the SHM region, 0 if heap.   */
    /* Always returns 0 on current hosts (shm_is_shm_handle is null).  */
    int32_t         (*shm_is_shm_handle)(xi_image_handle h);

    /* --------------------------------------------------------------- */
    /* File I/O (host-provided so plugins / scripts don't have to vendor
     * stb_image themselves). Reads PNG / JPEG / BMP / TGA / GIF /
     * PSD / HDR / PIC into a fresh image_create-allocated handle.
     * Returns 0 on failure (file missing, decode error, OOM).
     *
     * The returned handle has refcount 1; the caller is responsible
     * for image_release when done. */
    xi_image_handle (*read_image_file)(const char* path);

    /* --------------------------------------------------------------- */
    /* Publish a short sticky status string for this component (ABI-
     * additive; plugins built against an older header just never call
     * it, and an older host leaves it null — always null-check).
     *   source: the instance name (host attributes null/empty to "@plugin").
     *   text:   short human status, e.g. "grabbing" / "model loaded".
     * The host keeps the LATEST per source and serves it via cmd:status. */
    void            (*set_status)(const char* source, const char* text);

    /* (set_safe_state was REMOVED 2026-06. A comms plugin that needs a
     * "BE crashed -> tell the PLC" guarantee spawns its own sidecar process
     * which watches the BE's process handle and sends the line-safe message
     * itself on death — the core no longer brokers it.) */

    /* --------------------------------------------------------------- */
    /* In-process doc allocator (ABI v3, γ). Host-owned heap behind the */
    /* JSON doc, so a yyjson_mut_doc built through it is host-owned and  */
    /* its free (via doc->alc) returns to the host — mirrors            */
    /* image_create/addref/release for pixels, making a doc pointer      */
    /* safe to hand across the DLL boundary and free from either side.   */
    /* The plugin wraps these into a yyjson_alc. Null on a pre-v3 host  */
    /* (the doc path is then simply never taken — see record_to_c).      */
    /* v1 of this is plain malloc-backed; a pooled free-list is a later  */
    /* internal swap that needs no ABI change. */
    void*           (*doc_chunk_alloc)(size_t size);
    void*           (*doc_chunk_realloc)(void* ptr, size_t size);
    void            (*doc_chunk_free)(void* ptr);

    /* --------------------------------------------------------------- */
    /* In-process doc refcount (ABI v4, γ-4). Host-side reference count  */
    /* for a yyjson_mut_doc* handed across the ABI — the doc analogue of */
    /* image_addref/image_release. A doc shared across the boundary (the */
    /* host adopting a doc a plugin still caches, or a plugin retaining   */
    /* its borrowed input) is owned by the host registry; each holding    */
    /* side keeps one ref. The doc MUST have been built with doc_chunk_*  */
    /* (host-owned), so its free routes back via doc->alc.                */
    /*                                                                    */
    /*   doc_retain:  bump the refcount, creating the entry at 1 if the   */
    /*                doc is not yet registered. Idempotent per holder.   */
    /*   doc_release: drop one ref; when it reaches zero the host frees    */
    /*                the doc (yyjson_mut_doc_free via doc->alc).          */
    /*                                                                    */
    /* Null on a pre-v4 host (always null-check): callers then fall back  */
    /* to the v3 behaviour — deep-copy to retain, serialize to hand off.  */
    void            (*doc_retain)(void* doc);
    void            (*doc_release)(void* doc);
    /* Current host-side refcount for a shared doc (0 if unregistered). Lets the
     * adopting side learn whether ANOTHER side still holds it: >1 ⇒ shared
     * (adopt frozen, copy-on-write on mutate); <=1 ⇒ sole side (adopt writable,
     * no COW). Null on a pre-v4 host ⇒ adopt writable (the v3 transfer behaviour). */
    int32_t         (*doc_refcount)(void* doc);

    /* --------------------------------------------------------------- */
    /* emit_record (ABI v6) — the ONE plugin-facing dispatch verb. A    */
    /* source hands the host a whole record (images + metadata) under an */
    /* id; the host stages it and dispatches one inspection. The script  */
    /* reads it back via current_trigger().image()/.meta()/.id_string(). */
    /*                                                                   */
    /*   emitter: the staging instance's name (xi::Plugin::name()).      */
    /*   id:      caller-supplied 128-bit id; XI_TRIGGER_NULL asks the   */
    /*            host to mint a fresh one. Its hex form is id_string().  */
    /*   rec->images / rec->image_count: the frame(s); the host addrefs  */
    /*            each handle, so the caller may release right after.     */
    /*   rec->doc: a HOST-OWNED yyjson_mut_doc* enrolled via the host    */
    /*            doc registry — produced by the SDK's xi::emit_record(), */
    /*            which share_out()s it (reserving one ref for the host   */
    /*            to consume). Carried across the async dispatch by       */
    /*            pointer — zero serialize. A plugin-owned bare doc must  */
    /*            NOT be passed (use the SDK helper, which also guarantees */
    /*            the doc is built under the host allocator).             */
    /*   rec->data / rec->len: used only when rec->doc is NULL — parsed   */
    /*            once into a host-owned doc at emit time.                */
    /*   ts:     capture timestamp (µs, host clock); 0 = host's now.      */
    /*                                                                   */
    /* Multi-camera sync is a gathering plugin (one record, N images),   */
    /* not a host policy. Null on a pre-v6 host ⇒ use the SDK helper,    */
    /* which falls back to frames-only on older hosts. */
    void (*emit_record)(const char* emitter,
                        xi_trigger_id id,
                        const struct xi_record* rec,
                        int64_t ts);

    /* --------------------------------------------------------------- */
    /* emit_binary (ABI v8) — push an opaque binary frame straight to    */
    /* connected WS clients. The host is a dumb byte pipe: it forwards   */
    /* `len` bytes via the WS server's binary send and does NOT parse    */
    /* them. The FRAME FORMAT is entirely the plugin's contract with its */
    /* own UI/consumer (e.g. an output plugin that ships images live —   */
    /* no base64, no poll — with a self-describing header it defines).   */
    /* Safe to call from a dispatch worker thread (the WS send is        */
    /* thread-safe). Null on a pre-v8 host — always null-check; a plugin */
    /* then falls back to a pull path (exchange).                        */
    void (*emit_binary)(const void* data, int32_t len);

    /* --------------------------------------------------------------- */
    /* compress_image (ABI v9) — a generic JPEG-encode host service with */
    /* a content-addressed cache: the same image compressed by several   */
    /* plugins (or the same plugin repeatedly) is encoded ONCE globally. */
    /* The host keys a bounded (N-rotate) cache by a content hash of the */
    /* pixels: a hit returns the cached JPEG immediately; a miss encodes */
    /* + stores. Convenience only — a plugin that needs JPEG can use this*/
    /* instead of linking its own codec, and shares the encode of a      */
    /* buffer reused across the pipeline. Plugin-agnostic; the host does */
    /* not know or care what the bytes are for.                          */
    /*   pixels/w/h/channels: the source image (8-bit, 1/3/4 ch).        */
    /*   quality: 1..100.                                                */
    /*   out/out_cap: JPEG written here; returns bytes written, or       */
    /*     -needed if out_cap is too small (resize + retry), 0 on error. */
    /* Null on a pre-v9 host — plugin then encodes itself.               */
    int32_t (*compress_image)(const void* pixels, int32_t w, int32_t h,
                              int32_t channels, int32_t quality,
                              void* out, int32_t out_cap);
} xi_host_api;

/* ABI LAYOUT GUARD (host build only). The version gate elsewhere is an int compare
 * (plugin's requested version <= host's) — it does NOT verify struct layout. So a
 * well-meaning edit that changes xi_host_api WITHOUT bumping XI_ABI_VERSION (e.g.
 * deleting the always-null shm_* fields, which shifts every later function pointer)
 * would still pass the gate for an un-recompiled plugin and hand it a mis-offset
 * table -> silent call-through-wrong-pointer. This static_assert ties the layout to
 * the version: if you change the struct you MUST bump XI_ABI_VERSION above and update
 * the expected size here, which is the conscious "I changed the ABI" step. Fires only
 * in the C++ host build (where xi_abi.h is edited + the host rebuilt); a C plugin TU
 * just skips it. To refresh after an intentional change, read the size the compiler
 * reports when this fails. */
#if defined(__cplusplus)
#include <cstddef>
static_assert(sizeof(xi_host_api) == XI_ABI_EXPECTED_SIZE,
              "xi_host_api layout changed: bump XI_ABI_VERSION and update "
              "XI_ABI_EXPECTED_SIZE (see the ABI LAYOUT GUARD note).");
static_assert(offsetof(xi_host_api, compress_image) == XI_ABI_EXPECTED_SIZE - sizeof(void*),
              "compress_image is no longer the last field — a field was added/removed "
              "without updating the ABI guard; bump XI_ABI_VERSION.");
#endif

/* ------------------------------------------------------------------ */
/* Record — the universal data container crossing the boundary        */
/* ------------------------------------------------------------------ */

/* A record: named images + JSON metadata. */
typedef struct xi_record {
    const xi_record_image* images;
    int32_t                image_count;
    const uint8_t*         data;    /* yyjson JSON bytes — used iff doc == NULL */
    int32_t                len;     /* byte length of `data` */
    /* ABI v3 (γ): borrowed, READ-ONLY yyjson_mut_doc*. Non-null only for an
     * in-process call whose plugin's xi_yyjson_abi() matches the host's; the
     * callee reads it as a view (no parse) and must not mutate it (copy-on-
     * write into its own doc to change anything). NULL ⇒ use data/len. */
    const void*            doc;
} xi_record;

/* Output record — plugin fills this during process(). */
typedef struct {
    xi_record_image* images;
    int32_t          image_count;
    int32_t          image_capacity;
    const uint8_t*   data;          /* yyjson JSON bytes (tls-owned via record_to_c, or malloc'd) — used iff out_doc == NULL */
    int32_t          len;
    /* ABI v3 (γ) + v4 (γ-4): a yyjson_mut_doc* the caller ADOPTS (zero copy /
     * zero parse), built with the host doc allocator. Handed back as a SHARED,
     * host-refcounted doc (the caller adopt_shared's it): the plugin may keep a
     * cached ref, and the doc lives until the LAST side doc_release's it — the
     * doc analogue of image_addref/release. NULL ⇒ the caller reads data/len.
     * Never both. */
    void*            out_doc;
} xi_record_out;

/* Helpers for building output records */

static inline void xi_record_out_init(xi_record_out* out) {
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->data = NULL;
    out->len = 0;
    out->out_doc = NULL;   /* v3/v4: filled only on the in-process doc path (adopt_shared) */
}

static inline void xi_record_out_add_image(xi_record_out* out,
                                            const char* key,
                                            xi_image_handle handle) {
    if (out->image_count >= out->image_capacity) {
        int32_t new_cap = out->image_capacity ? out->image_capacity * 2 : 8;
        xi_record_image* arr = (xi_record_image*)realloc(
            out->images, (size_t)new_cap * sizeof(xi_record_image));
        if (!arr) return;
        out->images = arr;
        out->image_capacity = new_cap;
    }
    xi_record_image* entry = &out->images[out->image_count++];
    entry->key = _strdup(key);
    entry->handle = handle;
}

static inline void xi_record_out_set_data(xi_record_out* out, const uint8_t* data, int32_t len) {
    free((void*)out->data);
    uint8_t* copy = (uint8_t*)malloc((size_t)len);
    if (copy && data) memcpy(copy, data, (size_t)len);
    out->data = copy;
    out->len = copy ? len : 0;
}

/* Free strings the plugin allocated via the inline malloc/strdup
 * helpers above. SAFE TO CALL on outputs populated by `record_to_c`
 * (xi_abi.hpp) — `image_capacity == 0` signals "plugin-owned tls
 * storage; nothing to free", which is the path the C++ macro generates.
 *
 * Background: when these helpers are inlined into a plugin DLL that
 * uses a different CRT than the backend EXE, the plugin's `_strdup` /
 * `realloc` is paired with the backend's `free()` — undefined
 * behaviour. The C++ helpers in `xi_abi.hpp::record_to_c` route output
 * strings through thread-local storage owned by the plugin DLL, so no
 * cross-CRT free happens. Direct-C plugins that call
 * `xi_record_out_add_image` etc still use the malloc path and are
 * safe ONLY if the plugin and backend share a CRT (the CMake default
 * `/MD` does this). */
static inline void xi_record_out_free(xi_record_out* out) {
    if (out->image_capacity > 0) {
        /* Legacy / direct-C path: plugin used the realloc + strdup
         * helpers. Free with the same allocator the calling EXE was
         * compiled against (best effort; same-CRT contract). */
        for (int32_t i = 0; i < out->image_count; ++i) {
            free((void*)out->images[i].key);
        }
        free(out->images);
        free((void*)out->data);
    }
    /* image_capacity == 0: plugin-owned thread-local storage, no free. */
    /* out_doc is NOT freed here: on the v3 doc path the C++ caller ADOPTS it
     * (takes the ref) before calling this, so freeing it would be a
     * use-after-free. Just clear the pointer. */
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->data = NULL;
    out->len = 0;
    out->out_doc = NULL;
}

/* ------------------------------------------------------------------ */
/* Plugin entry points — exported by every plugin DLL                 */
/* ------------------------------------------------------------------ */

/*
 * xi_plugin_create(host, name) → opaque instance pointer
 *   Called once per instance. Plugin stores the host_api pointer for
 *   later use (image_create, image_data, etc.)
 *
 * xi_plugin_destroy(inst)
 *   Release all cached handles and free the instance.
 *
 * xi_plugin_process(inst, input, output)
 *   Run the plugin's core logic. Read input images via host->image_data().
 *   Create output images via host->image_create(). Put handles in output.
 *
 * xi_plugin_exchange(inst, cmd_json, rsp_buf, rsp_buflen) → bytes written
 *   UI/config commands. Returns JSON response.
 *
 * xi_plugin_get_def(inst, buf, buflen) → bytes written
 *   Serialize current config to JSON.
 *
 * xi_plugin_set_def(inst, json) → 0 on success
 *   Restore config from JSON.
 */

/* Type signatures for GetProcAddress */
typedef void* (*xi_plugin_create_fn)(const xi_host_api* host, const char* name);
typedef void  (*xi_plugin_destroy_fn)(void* inst);
typedef void  (*xi_plugin_process_fn)(void* inst, const xi_record* input, xi_record_out* output);
typedef int   (*xi_plugin_exchange_fn)(void* inst, const char* cmd, char* rsp, int rsplen);
typedef int   (*xi_plugin_get_def_fn)(void* inst, char* buf, int buflen);
typedef int   (*xi_plugin_set_def_fn)(void* inst, const char* json);
/* ABI v7 — OPTIONAL (null if the plugin didn't opt in via XI_PLUGIN_STAGED).
 *   xi_plugin_prepare(inst, def_json, folder) -> 0 on success. Loads heavy
 *     assets into a background staging slot; called UNGATED (concurrent with
 *     process), so it MUST touch only staging, never live state.
 *   xi_plugin_commit(inst). Atomically swaps staging -> live; called gated. */
typedef int   (*xi_plugin_prepare_fn)(void* inst, const char* def_json, const char* folder);
typedef void  (*xi_plugin_commit_fn)(void* inst);

#ifdef __cplusplus
}
#endif

#endif /* XI_ABI_H */
