/*
 * xi_abi.h — the universal plugin interface for xInsp2.
 *
 * ALL plugins use this interface — built-in, third-party, native scripts.
 * Pure C types at the boundary. Stable across compiler versions.
 *
 * Key concept: images are refcounted HANDLES managed by the host.
 * Plugins never malloc/free image buffers — they ask the host to create
 * images, get a handle back, read/write via the host API, and release
 * when done. Caching = addref. Passing between plugins = zero copy
 * (just pass the handle).
 *
 * Flow:
 *
 *   1. Backend loads plugin DLL
 *   2. Calls xi_plugin_create(host_api, name) → opaque instance
 *   3. Calls xi_plugin_process(inst, input_record, output_record)
 *      - input images are handles the backend owns
 *      - plugin reads via host->image_data(handle)
 *      - plugin creates output images via host->image_create()
 *      - plugin puts output handles in the output record
 *      - to cache an input image: host->image_addref(handle)
 *   4. Backend reads output record, takes ownership of output handles
 *   5. When done: host->image_release() on all handles
 */

#ifndef XI_ABI_H
#define XI_ABI_H

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* ABI version — bumped on any semantic change to the surfaces       */
/* below. Plugins compiled against version N require a host with     */
/* version >= N (forward compatible — newer host runs older          */
/* plugin), but a host running a plugin compiled against a newer     */
/* version than itself may see null fn pointers in xi_host_api.      */
/*                                                                    */
/* The plugin loader gates on this: a plugin's xi_plugin_abi_version */
/* export (generated by XI_PLUGIN_IMPL) is checked against the       */
/* host's XI_ABI_VERSION and the plugin is refused if it asks for a  */
/* newer ABI than the host provides.                                  */
/*                                                                    */
/* Current version history:                                           */
/*   1 — initial frozen surface (image pool, trigger bus, SHM [fields  */
/*       retained for layout stability; SHM removed 2026-05, always  */
/*       null on current hosts], host api with read_image_file).     */
/*   2 — + emit_resource (emit/fetch resource store). Additive at the */
/*       struct tail, so v1 plugins keep working unchanged.          */
/*   3 — + in-process doc pass-by-pointer (γ): xi_record.doc /        */
/*       xi_record_out.out_doc carry a borrowed/host-owned           */
/*       yyjson_mut_doc* so an in-process call skips the JSON         */
/*       serialize round-trip; doc_chunk_* host allocator backs       */
/*       host-owned docs; the xi_yyjson_abi() plugin export gates it  */
/*       on a matching yyjson layout. All additive at the tail; when  */
/*       the doc pointer is null (older plugin / mismatch / cross-    */
/*       process) the data/len JSON path is used exactly as in v2.    */
/*   4 — + doc_retain/doc_release/doc_refcount (γ-4): a host-side     */
/*       refcount for a yyjson_mut_doc handed across the ABI,         */
/*       mirroring image_addref/release. Lets a doc pointer be held   */
/*       by more than one side (host adopting a doc a plugin still    */
/*       caches; a plugin caching its borrowed input) with no deep    */
/*       copy; doc_refcount lets the adopter learn if it is the sole  */
/*       side. Additive at the tail; null on a pre-v4 host ⇒ callers  */
/*       fall back to the v3 deep-copy / serialize behaviour.         */
/* ------------------------------------------------------------------ */
#define XI_ABI_VERSION 4

/* ------------------------------------------------------------------ */
/* Image handle — opaque reference to a refcounted image in the host  */
/* ------------------------------------------------------------------ */

typedef uint64_t xi_image_handle;
#define XI_IMAGE_NULL 0

/* ------------------------------------------------------------------ */
/* Trigger ID — 128-bit identifier for a single inspection event.     */
/* Sources tag every emitted frame with one. Frames sharing a tid are */
/* correlated (e.g., synchronized multi-camera capture). The host's   */
/* TriggerBus groups them and dispatches the script once per tid.     */
/* ------------------------------------------------------------------ */

typedef struct { uint64_t hi; uint64_t lo; } xi_trigger_id;

#ifdef __cplusplus
#define XI_TRIGGER_NULL (xi_trigger_id{0, 0})
#else
#define XI_TRIGGER_NULL ((xi_trigger_id){0, 0})
#endif

static inline int xi_trigger_id_eq(xi_trigger_id a, xi_trigger_id b) {
    return a.hi == b.hi && a.lo == b.lo;
}
static inline int xi_trigger_id_is_null(xi_trigger_id a) {
    return a.hi == 0 && a.lo == 0;
}

/* ------------------------------------------------------------------ */
/* Record image entry — defined before xi_host_api so emit_trigger    */
/* can reference it.                                                  */
/* ------------------------------------------------------------------ */

typedef struct {
    const char*      key;       /* borrowed — valid for duration of the call */
    xi_image_handle  handle;
} xi_record_image;

/* ------------------------------------------------------------------ */
/* Host API — function table provided by the backend to every plugin  */
/* ------------------------------------------------------------------ */

typedef struct xi_host_api {
    /* Image pool */
    xi_image_handle (*image_create)(int32_t w, int32_t h, int32_t channels);
    void            (*image_addref)(xi_image_handle h);
    void            (*image_release)(xi_image_handle h);
    uint8_t*        (*image_data)(xi_image_handle h);
    int32_t         (*image_width)(xi_image_handle h);
    int32_t         (*image_height)(xi_image_handle h);
    int32_t         (*image_channels)(xi_image_handle h);
    int32_t         (*image_stride)(xi_image_handle h);

    /* Logging */
    void (*log)(int32_t level, const char* msg);
    /* level: 0=debug, 1=info, 2=warn, 3=error */

    /* Lookup the on-disk folder for a named instance. The folder is
     * created by the host before xi_plugin_create() is called and is the
     * right place to persist plugin-specific data (calibration files,
     * lookup tables, captured frames, ML weights — anything beyond the
     * small JSON config returned by get_def).
     *
     * Writes the path (without trailing slash) into buf, returns bytes
     * written, or -needed if buflen is too small. Returns 0 if the
     * instance is unknown to the host. */
    int32_t (*instance_folder)(const char* instance_name, char* buf, int32_t buflen);

    /* Image-source plugins call this to publish a frame (or set of
     * frames) tagged with a trigger ID. The host's TriggerBus groups
     * frames sharing a tid and dispatches the script once per complete
     * trigger.
     *
     *   source_name:   the publishing instance's name (xi::Plugin::name())
     *   tid:           caller-supplied 128-bit identifier; XI_TRIGGER_NULL
     *                  asks the host to allocate a fresh one.
     *   timestamp_us:  capture timestamp in microseconds (host clock).
     *                  Pass 0 to use the host's current time.
     *   images:        the frame(s) being published. The bus addrefs each
     *                  handle internally — the caller may release them
     *                  immediately after this call returns.
     *   image_count:   number of entries in `images`.
     */
    void (*emit_trigger)(const char* source_name,
                         xi_trigger_id tid,
                         int64_t timestamp_us,
                         const xi_record_image* images,
                         int32_t image_count);

    /* --------------------------------------------------------------- */
    /* SHM zero-copy buffer pool — RETAINED FOR ABI STABILITY ONLY.   */
    /* SHM and the out-of-process comms gateway were removed 2026-05.  */
    /* ALL five function pointers below are NULL on current hosts and  */
    /* will remain NULL until/unless SHM is re-introduced. Plugins     */
    /* MUST null-check before calling (as the original contract         */
    /* already required). Fields are kept in place — removing them     */
    /* would shift every subsequent function pointer and break binary   */
    /* compatibility with plugins compiled against ABI v1/v2.          */
    /*                                                                  */
    /* Historical note: these were intended to allow a worker process   */
    /* or different plugin to deref image buffers without a memcpy.     */
    /* The opt-in design (null == unavailable) means existing code      */
    /* that already null-checks continues to work with no change.       */
    /*                                                                  */
    /*   size_bytes for shm_alloc_buffer: opaque byte buffer (e.g.     */
    /*     ML weights, big metadata). image_data() returns the start.  */
    /*                                                                  */
    /* Refcount semantics (when non-null) match image_addref/release.   */
    /* --------------------------------------------------------------- */
    xi_image_handle (*shm_create_image)(int32_t w, int32_t h, int32_t channels);
    xi_image_handle (*shm_alloc_buffer)(int32_t size_bytes);
    void            (*shm_addref)(xi_image_handle h);
    void            (*shm_release)(xi_image_handle h);
    /* Returns 1 if the handle came from the SHM region, 0 if heap.   */
    /* Always returns 0 on current hosts (shm_is_shm_handle is null).  */
    int32_t         (*shm_is_shm_handle)(xi_image_handle h);

    /* --------------------------------------------------------------- */
    /* File I/O (host-provided so plugins / scripts don't have to vendor
     * stb_image themselves). Reads PNG / JPEG / BMP / TGA / GIF /
     * PSD / HDR / PIC into a fresh image_create-allocated handle.
     * Returns 0 on failure (file missing, decode error, OOM).
     *
     * The returned handle has refcount 1; the caller is responsible
     * for image_release when done. */
    xi_image_handle (*read_image_file)(const char* path);

    /* --------------------------------------------------------------- */
    /* Publish a short sticky status string for this component (ABI-
     * additive; plugins built against an older header just never call
     * it, and an older host leaves it null — always null-check).
     *   source: the instance name (host attributes null/empty to "@plugin").
     *   text:   short human status, e.g. "grabbing" / "model loaded".
     * The host keeps the LATEST per source and serves it via cmd:status. */
    void            (*set_status)(const char* source, const char* text);

    /* --------------------------------------------------------------- */
    /* emit/fetch resource store (v2). Backs the emit/fetch dispatch model:
     * an emitter STAGES a frame — named images + cJSON metadata — under
     * an opaque string res_id; a consumer FETCHES it later by res_id. The
     * host keeps a bounded per-emitter ring. ABI-additive: plugins built
     * against an older header never call it; an older host leaves it null
     * (always null-check before use).
     *
     *   emitter_name: the staging instance's name.
     *   res_id:       opaque id (may be a UUID); the fetch + replay key.
     *                 Ordering for downstream serialization rides as a
     *                 `seq` field inside `cjson`, not here.
     *   images:       frame(s) to stage; the store addrefs each handle, so
     *                 the caller may release them right after this returns.
     *   cjson:        metadata blob (may be null/empty).
     * (The fetch_resource entry is added alongside the use() proxy.) */
    void            (*emit_resource)(const char* emitter_name, const char* res_id,
                                     const xi_record_image* images, int32_t image_count,
                                     const char* cjson);

    /* Pull a staged resource's metadata by res_id. Writes the cJSON into
     * cjson_buf and returns its byte length L: L >= 0 means the resource
     * exists (the L bytes were written iff L <= cjson_buflen — otherwise
     * nothing is written; resize to L and retry); -1 means res_id is not
     * staged for this emitter. Does NOT touch image refcounts. */
    int32_t         (*fetch_resource)(const char* emitter_name, const char* res_id,
                                    char* cjson_buf, int32_t cjson_buflen);

    /* Pull one staged image by key. Returns an addref'd handle (caller
     * image_release when done) or XI_IMAGE_NULL if the resource or key is
     * absent. Lazy: a consumer fetches only the images it needs. */
    xi_image_handle (*fetch_image)(const char* emitter_name, const char* res_id,
                                          const char* key);

    /* Drive one inspection for a staged resource (emit/fetch dispatch). The
     * emitter calls this AFTER emit_resource to signal "run res_id now"; the
     * host routes an id-only event into the emitter's lane (by its group),
     * bypassing trigger-bus correlation. The script reads the id back via
     * xi::current_trigger().id_string() and fetches with xi::use(emitter).fetch(id).
     *   res_id:       128-bit id carried as the run's trigger id; its hex form
     *                 (id_string) is the res_id key used for emit_resource.
     *   timestamp_us: capture time (0 = host's current time).
     * Returns 1 if the run was accepted (enqueued / dispatched), 0 if the lane
     * was full or dispatch isn't running. The lane does NOT silently drop — on a
     * 0 the EMITTER owns the back-pressure choice (skip this frame at the source
     * before burning a seq, or retry), which is what keeps a downstream seq
     * stream gap-free. */
    int32_t         (*emit_dispatch)(const char* emitter_name, xi_trigger_id res_id,
                                     int64_t timestamp_us);

    /* Register an emergency PLC payload for the BE-crash case. The host persists
     * it (atomically) to a file the supervising xinsp-fe watches; if THIS backend
     * dies, the FE — which survives the crash and owns the PLC safe-state sink —
     * forwards the payload to the PLC. This is how a comms plugin keeps the
     * "BE crashed -> tell the PLC" guarantee without living out-of-process.
     * Call again to update; pass "" to clear. Null/no-op if unsupported (e.g.
     * the headless runner with no FE). */
    void            (*set_safe_state)(const char* payload);

    /* --------------------------------------------------------------- */
    /* In-process doc allocator (ABI v3, γ). Host-owned heap behind the */
    /* JSON doc, so a yyjson_mut_doc built through it is host-owned and  */
    /* its free (via doc->alc) returns to the host — mirrors            */
    /* image_create/addref/release for pixels, making a doc pointer      */
    /* safe to hand across the DLL boundary and free from either side.   */
    /* The plugin wraps these into a yyjson_alc. Null on a pre-v3 host  */
    /* (the doc path is then simply never taken — see record_to_c).      */
    /* v1 of this is plain malloc-backed; a pooled free-list is a later  */
    /* internal swap that needs no ABI change. */
    void*           (*doc_chunk_alloc)(size_t size);
    void*           (*doc_chunk_realloc)(void* ptr, size_t size);
    void            (*doc_chunk_free)(void* ptr);

    /* --------------------------------------------------------------- */
    /* In-process doc refcount (ABI v4, γ-4). Host-side reference count  */
    /* for a yyjson_mut_doc* handed across the ABI — the doc analogue of */
    /* image_addref/image_release. A doc shared across the boundary (the */
    /* host adopting a doc a plugin still caches, or a plugin retaining   */
    /* its borrowed input) is owned by the host registry; each holding    */
    /* side keeps one ref. The doc MUST have been built with doc_chunk_*  */
    /* (host-owned), so its free routes back via doc->alc.                */
    /*                                                                    */
    /*   doc_retain:  bump the refcount, creating the entry at 1 if the   */
    /*                doc is not yet registered. Idempotent per holder.   */
    /*   doc_release: drop one ref; when it reaches zero the host frees    */
    /*                the doc (yyjson_mut_doc_free via doc->alc).          */
    /*                                                                    */
    /* Null on a pre-v4 host (always null-check): callers then fall back  */
    /* to the v3 behaviour — deep-copy to retain, serialize to hand off.  */
    void            (*doc_retain)(void* doc);
    void            (*doc_release)(void* doc);
    /* Current host-side refcount for a shared doc (0 if unregistered). Lets the
     * adopting side learn whether ANOTHER side still holds it: >1 ⇒ shared
     * (adopt frozen, copy-on-write on mutate); <=1 ⇒ sole side (adopt writable,
     * no COW). Null on a pre-v4 host ⇒ adopt writable (the v3 transfer behaviour). */
    int32_t         (*doc_refcount)(void* doc);
} xi_host_api;

/* ------------------------------------------------------------------ */
/* Record — the universal data container crossing the boundary        */
/* ------------------------------------------------------------------ */

/* A record: named images + JSON metadata. */
typedef struct {
    const xi_record_image* images;
    int32_t                image_count;
    const uint8_t*         data;    /* yyjson JSON bytes — used iff doc == NULL */
    int32_t                len;     /* byte length of `data` */
    /* ABI v3 (γ): borrowed, READ-ONLY yyjson_mut_doc*. Non-null only for an
     * in-process call whose plugin's xi_yyjson_abi() matches the host's; the
     * callee reads it as a view (no parse) and must not mutate it (copy-on-
     * write into its own doc to change anything). NULL ⇒ use data/len. */
    const void*            doc;
} xi_record;

/* Output record — plugin fills this during process(). */
typedef struct {
    xi_record_image* images;
    int32_t          image_count;
    int32_t          image_capacity;
    const uint8_t*   data;          /* yyjson JSON bytes (tls-owned via record_to_c, or malloc'd) — used iff out_doc == NULL */
    int32_t          len;
    /* ABI v3 (γ) + v4 (γ-4): a yyjson_mut_doc* the caller ADOPTS (zero copy /
     * zero parse), built with the host doc allocator. Handed back as a SHARED,
     * host-refcounted doc (the caller adopt_shared's it): the plugin may keep a
     * cached ref, and the doc lives until the LAST side doc_release's it — the
     * doc analogue of image_addref/release. NULL ⇒ the caller reads data/len.
     * Never both. */
    void*            out_doc;
} xi_record_out;

/* Helpers for building output records */

static inline void xi_record_out_init(xi_record_out* out) {
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->data = NULL;
    out->len = 0;
    out->out_doc = NULL;   /* v3/v4: filled only on the in-process doc path (adopt_shared) */
}

static inline void xi_record_out_add_image(xi_record_out* out,
                                            const char* key,
                                            xi_image_handle handle) {
    if (out->image_count >= out->image_capacity) {
        int32_t new_cap = out->image_capacity ? out->image_capacity * 2 : 8;
        xi_record_image* arr = (xi_record_image*)realloc(
            out->images, (size_t)new_cap * sizeof(xi_record_image));
        if (!arr) return;
        out->images = arr;
        out->image_capacity = new_cap;
    }
    xi_record_image* entry = &out->images[out->image_count++];
    entry->key = _strdup(key);
    entry->handle = handle;
}

static inline void xi_record_out_set_data(xi_record_out* out, const uint8_t* data, int32_t len) {
    free((void*)out->data);
    uint8_t* copy = (uint8_t*)malloc((size_t)len);
    if (copy && data) memcpy(copy, data, (size_t)len);
    out->data = copy;
    out->len = copy ? len : 0;
}

/* Free strings the plugin allocated via the inline malloc/strdup
 * helpers above. SAFE TO CALL on outputs populated by `record_to_c`
 * (xi_abi.hpp) — `image_capacity == 0` signals "plugin-owned tls
 * storage; nothing to free", which is the path the C++ macro generates.
 *
 * Background: when these helpers are inlined into a plugin DLL that
 * uses a different CRT than the backend EXE, the plugin's `_strdup` /
 * `realloc` is paired with the backend's `free()` — undefined
 * behaviour. The C++ helpers in `xi_abi.hpp::record_to_c` route output
 * strings through thread-local storage owned by the plugin DLL, so no
 * cross-CRT free happens. Direct-C plugins that call
 * `xi_record_out_add_image` etc still use the malloc path and are
 * safe ONLY if the plugin and backend share a CRT (the CMake default
 * `/MD` does this). */
static inline void xi_record_out_free(xi_record_out* out) {
    if (out->image_capacity > 0) {
        /* Legacy / direct-C path: plugin used the realloc + strdup
         * helpers. Free with the same allocator the calling EXE was
         * compiled against (best effort; same-CRT contract). */
        for (int32_t i = 0; i < out->image_count; ++i) {
            free((void*)out->images[i].key);
        }
        free(out->images);
        free((void*)out->data);
    }
    /* image_capacity == 0: plugin-owned thread-local storage, no free. */
    /* out_doc is NOT freed here: on the v3 doc path the C++ caller ADOPTS it
     * (takes the ref) before calling this, so freeing it would be a
     * use-after-free. Just clear the pointer. */
    out->images = NULL;
    out->image_count = 0;
    out->image_capacity = 0;
    out->data = NULL;
    out->len = 0;
    out->out_doc = NULL;
}

/* ------------------------------------------------------------------ */
/* Plugin entry points — exported by every plugin DLL                 */
/* ------------------------------------------------------------------ */

/*
 * xi_plugin_create(host, name) → opaque instance pointer
 *   Called once per instance. Plugin stores the host_api pointer for
 *   later use (image_create, image_data, etc.)
 *
 * xi_plugin_destroy(inst)
 *   Release all cached handles and free the instance.
 *
 * xi_plugin_process(inst, input, output)
 *   Run the plugin's core logic. Read input images via host->image_data().
 *   Create output images via host->image_create(). Put handles in output.
 *
 * xi_plugin_exchange(inst, cmd_json, rsp_buf, rsp_buflen) → bytes written
 *   UI/config commands. Returns JSON response.
 *
 * xi_plugin_get_def(inst, buf, buflen) → bytes written
 *   Serialize current config to JSON.
 *
 * xi_plugin_set_def(inst, json) → 0 on success
 *   Restore config from JSON.
 */

/* Type signatures for GetProcAddress */
typedef void* (*xi_plugin_create_fn)(const xi_host_api* host, const char* name);
typedef void  (*xi_plugin_destroy_fn)(void* inst);
typedef void  (*xi_plugin_process_fn)(void* inst, const xi_record* input, xi_record_out* output);
typedef int   (*xi_plugin_exchange_fn)(void* inst, const char* cmd, char* rsp, int rsplen);
typedef int   (*xi_plugin_get_def_fn)(void* inst, char* buf, int buflen);
typedef int   (*xi_plugin_set_def_fn)(void* inst, const char* json);

#ifdef __cplusplus
}
#endif

#endif /* XI_ABI_H */
